"""SYNTHETIC transport/corruption fixtures, not live socket or restart evidence.

Successful bodies are generated by actual local dataset/context/diagnostic/rules
producers. HTTP is mocked; no business order, score, or wording is pinned here.
"""
from contextlib import redirect_stderr, redirect_stdout
from copy import deepcopy
from io import BytesIO, StringIO
import json
import unittest
from urllib.error import HTTPError, URLError
from urllib.parse import urlsplit

from backend.api import smoke_demo
from backend.decision.ranking import rank_deals
from backend.graph.analysis import analyze_deal_initial, analyze_pipeline_initial
from backend.graph.context import build_deal_context
from backend.ingestion.deals import list_deals


SECRET = 'SYNTHETIC-do-not-print-provider-secret'


class SyntheticResponse(BytesIO):
    def __init__(self, body, status):
        super().__init__(body)
        self.status = status

    def getcode(self):
        return self.status


class SyntheticTransport:
    """urllib-compatible isolated response map; never opens a network socket."""
    def __init__(self, payloads, prefix=''):
        self.payloads = deepcopy(payloads)
        self.prefix = prefix
        self.calls = []

    def __call__(self, request, *, timeout):
        path = urlsplit(request.full_url).path
        self.calls.append((path, request.get_method(), timeout))
        if self.prefix:
            path = path.removeprefix(self.prefix)
        status, payload = self.payloads[path]
        body = payload if isinstance(payload, bytes) else json.dumps(payload, ensure_ascii=False).encode('utf-8')
        if status != 200:
            raise HTTPError(request.full_url, status, SECRET, {}, BytesIO(body))
        return SyntheticResponse(body, status)


class SmokeDemoSyntheticTransportTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        deals = list_deals()
        contexts = [build_deal_context(deal.deal_id) for deal in deals]
        pipeline = {'schema_version': 'v1', **analyze_pipeline_initial()}
        # This local invocation builds a TEST fixture only; smoke_demo never calls it.
        priorities = rank_deals(deepcopy(contexts), deepcopy(pipeline['deals']))
        cls.payloads = {
            '/health': (200, dict(status='ok', schema_version='v1', snapshot_date='2026-10-01')),
            '/api/deals': (200, dict(schema_version='v1', snapshot_date='2026-10-01',
                                     items=[deal.model_dump() for deal in deals])),
            '/api/pipeline/initial-analysis': (200, pipeline),
            '/api/pipeline/priorities': (200, priorities),
            '/api/deals/DL-999/initial-analysis': (404, {'detail': {'code': 'DEAL_NOT_FOUND', 'message': SECRET}}),
        }
        for context in contexts:
            path = f'/api/deals/{context.deal.deal_id}'
            cls.payloads[path] = (200, context.model_dump())
            cls.payloads[path + '/initial-analysis'] = (200, {'schema_version': 'v1', **analyze_deal_initial(context)})

    def invoke(self, transport, base_url='http://synthetic.invalid', timeout=2.5):
        output = StringIO()
        status = smoke_demo.run_checks(base_url, timeout, opener=transport, output=output)
        return status, output.getvalue()

    def assert_failure(self, transport, endpoint=None, category=None):
        status, output = self.invoke(transport)
        self.assertNotEqual(status, 0)
        self.assertNotIn(SECRET, output)
        self.assertNotIn('synthetic.invalid', output)
        if endpoint is not None:
            self.assertIn(f'endpoint={endpoint}', output)
        if category is not None:
            self.assertIn(f'category={category}', output)
        return output

    def changed(self, path):
        transport = SyntheticTransport(self.payloads)
        return transport, transport.payloads[path][1]

    def test_complete_producer_case_accepts_p05_business_gaps_without_metric_errors(self):
        transport = SyntheticTransport(self.payloads, prefix='/demo')
        status, output = self.invoke(transport, base_url='https://synthetic.invalid/demo/')
        self.assertEqual(status, 0)
        self.assertNotIn(SECRET, output)

    def test_each_invocation_queries_transport_again_without_response_cache(self):
        transport = SyntheticTransport(self.payloads)
        self.assertEqual(self.invoke(transport)[0], 0)
        transport.payloads['/health'] = (503, {'detail': SECRET})
        self.assert_failure(transport, '/health', 'http')

    def test_synthetic_unreachable_transport_has_safe_nonzero_result(self):
        def unreachable(request, *, timeout):
            raise URLError(SECRET)
        self.assert_failure(unreachable, '/health', 'transport')

    def test_synthetic_http_failures_are_not_hidden_at_any_required_endpoint(self):
        for path in self.payloads:
            with self.subTest(endpoint=path):
                transport = SyntheticTransport(self.payloads)
                transport.payloads[path] = (503, {'detail': SECRET})
                output = self.assert_failure(transport, path, 'http')
                self.assertIn('status=503', output)
        for status in (301, 501):
            with self.subTest(status=status):
                transport = SyntheticTransport(self.payloads)
                transport.payloads['/api/pipeline/priorities'] = (status, {'detail': SECRET})
                self.assert_failure(transport, '/api/pipeline/priorities', 'http')

    def test_synthetic_malformed_and_nonfinite_json_fail_safely(self):
        for payload in (SECRET.encode(), {'status': 'ok', 'secret': SECRET, 'extra': float('nan')},
                        {'extra': float('inf')}, {'extra': float('-inf')}):
            with self.subTest(payload_type=type(payload).__name__):
                transport = SyntheticTransport(self.payloads)
                transport.payloads['/health'] = (200, payload)
                self.assert_failure(transport, '/health', 'json')

    def test_synthetic_incomplete_and_wrong_snapshot_payloads_fail(self):
        for path in self.payloads:
            with self.subTest(endpoint=path):
                transport = SyntheticTransport(self.payloads)
                transport.payloads[path] = (self.payloads[path][0], {})
                self.assert_failure(transport, path, 'validation')
        transport, payload = self.changed('/api/deals')
        payload['snapshot_date'] = '2026-09-01'
        self.assert_failure(transport, '/api/deals', 'validation')

    def test_synthetic_list_missing_duplicate_or_fabricated_deals_fail(self):
        for variant in ('missing', 'duplicate', 'fabricated'):
            with self.subTest(variant=variant):
                transport, payload = self.changed('/api/deals')
                if variant == 'missing':
                    payload['items'].pop()
                elif variant == 'duplicate':
                    payload['items'][-1] = deepcopy(payload['items'][0])
                else:
                    payload['items'][0]['account_name'] = SECRET
                self.assert_failure(transport, '/api/deals', 'validation')

    def test_synthetic_graph_mutations_are_checked_against_local_canonical_context(self):
        path = '/api/deals/DL-002'
        for variant in ('edge', 'node', 'missing'):
            with self.subTest(variant=variant):
                transport, payload = self.changed(path)
                if variant == 'edge':
                    payload['graph']['edges'][0]['relation'] = SECRET
                elif variant == 'node':
                    payload['graph']['nodes'][0]['label'] = SECRET
                else:
                    del payload['graph']
                self.assert_failure(transport, path, 'validation')

    def test_synthetic_source_record_corruption_fails_in_all_evidence_payloads(self):
        for path in ('/api/deals/DL-002', '/api/deals/DL-002/initial-analysis', '/api/pipeline/priorities'):
            with self.subTest(endpoint=path):
                transport, payload = self.changed(path)
                records = payload['items'][0]['evidence'] if 'items' in payload else payload['evidence']
                records[0]['excerpt'] = json.dumps({'synthetic_secret': SECRET})
                self.assert_failure(transport, path, 'validation')

    def test_synthetic_unregistered_evidence_and_impossible_priority_path_fail(self):
        path = '/api/pipeline/priorities'
        for variant in ('evidence', 'path'):
            with self.subTest(variant=variant):
                transport, payload = self.changed(path)
                item = payload['items'][0]
                if variant == 'evidence':
                    item['recommendation']['evidence_ids'].append('synthetic:unregistered')
                else:
                    item['evidence_paths'][0]['node_ids'][0] = 'synthetic:invented-node'
                self.assert_failure(transport, path, 'validation')

    def test_synthetic_pipeline_single_response_disagreement_fails(self):
        path = '/api/pipeline/initial-analysis'
        transport, payload = self.changed(path)
        # This is still valid diagnostic prose, but no longer the single response.
        payload['deals'][0]['boundaries'].append('SYNTHETIC inconsistent response')
        self.assert_failure(transport, path, 'validation')

    def test_synthetic_pipeline_missing_deal_and_fabricated_outlier_fail(self):
        path = '/api/pipeline/initial-analysis'
        for variant in ('missing', 'outlier'):
            with self.subTest(variant=variant):
                transport, payload = self.changed(path)
                if variant == 'missing':
                    payload['deals'].pop()
                else:
                    payload['statistical_assessment']['outlier_deal_ids'] = ['DL-005']
                self.assert_failure(transport, path, 'validation')

    def test_synthetic_p02_missing_gate_or_request_evidence_fails(self):
        path = '/api/pipeline/priorities'
        for variant in ('approval', 'evidence', 'pending'):
            with self.subTest(variant=variant):
                transport, payload = self.changed(path)
                item = next(item for item in payload['items'] if item['account_id'] == 'P02')
                if variant == 'approval':
                    item['recommendation']['approvals_needed'] = []
                elif variant == 'evidence':
                    item['recommendation']['evidence_ids'].remove('interactions.jsonl:I0348')
                else:
                    gate = next(factor for factor in item['factors'] if factor['name'] == 'gate_approval_izin')
                    gate['value'] = 'SYNTHETIC approved VP Sales'
                self.assert_failure(transport, path, 'validation')

    def test_synthetic_p02_diagnostic_request_missing_fails(self):
        path = '/api/deals/DL-002/initial-analysis'
        transport, payload = self.changed(path)
        payload['findings'] = [finding for finding in payload['findings']
                               if finding.get('requested_discount_pct') != '20']
        self.assert_failure(transport, path, 'validation')

    def test_p05_diagnostic_requires_missing_business_information(self):
        path = '/api/deals/DL-005/initial-analysis'
        transport, payload = self.changed(path)
        for finding in payload['findings']:
            finding['missing_information'] = []
        self.assert_failure(transport, path, 'validation')

    def test_synthetic_p05_discovery_insufficient_unknowns_and_null_score_are_required(self):
        path = '/api/pipeline/priorities'
        for variant in ('tier', 'status', 'unknowns', 'score'):
            with self.subTest(variant=variant):
                transport, payload = self.changed(path)
                item = next(item for item in payload['items'] if item['account_id'] == 'P05')
                if variant == 'tier':
                    item['priority_kind'] = 'acceleration'
                elif variant == 'status':
                    item['analysis_status'] = 'ready'
                elif variant == 'unknowns':
                    item['recommendation']['unknowns'] = []
                else:
                    next(factor for factor in item['factors'] if factor['name'] == 'skor_prioritas')['value'] = 0
                self.assert_failure(transport, path, 'validation')

    def test_synthetic_unknown_deal_requires_actual_404_and_not_found_code(self):
        path = '/api/deals/DL-999/initial-analysis'
        for status, payload in ((200, {'detail': {'code': 'DEAL_NOT_FOUND'}}),
                                (404, {'detail': {'code': 'SYNTHETIC_WRONG_CODE'}})):
            with self.subTest(status=status):
                transport = SyntheticTransport(self.payloads)
                transport.payloads[path] = (status, payload)
                self.assert_failure(transport, path)

    def test_invalid_base_urls_are_rejected_without_leaking_secrets(self):
        for url in (f'http://user:{SECRET}@synthetic.invalid', f'http://synthetic.invalid?key={SECRET}',
                    f'http://synthetic.invalid#{SECRET}', 'ftp://synthetic.invalid', 'http:///missing-host',
                    'http://synthetic.invalid:0', 'http://synthetic.invalid:65536',
                    'http://synthetic.invalid\n/hidden', 'http://synthetic.invalid\\hidden'):
            with self.subTest(url_kind=url.split(':', 1)[0]):
                transport = SyntheticTransport(self.payloads)
                status, output = self.invoke(transport, base_url=url)
                self.assertNotEqual(status, 0)
                self.assertEqual(transport.calls, [])
                self.assertNotIn(SECRET, output)
                self.assertIn('category=configuration', output)

    def test_timeout_bounds_reject_invalid_values_without_transport(self):
        for timeout in (0, -1, 60.01, float('nan'), float('inf'), SECRET):
            with self.subTest(timeout_type=type(timeout).__name__):
                transport = SyntheticTransport(self.payloads)
                status, output = self.invoke(transport, timeout=timeout)
                self.assertNotEqual(status, 0)
                self.assertEqual(transport.calls, [])
                self.assertNotIn(SECRET, output)

    def test_cli_argument_failures_return_integer_and_never_echo_credentials(self):
        for args in (['--base-url', f'http://user:{SECRET}@synthetic.invalid'],
                     ['--base-url', 'http://synthetic.invalid', '--timeout', SECRET],
                     ['--base-url', 'http://synthetic.invalid', '--timeout', 'nan'],
                     ['--unexpected', SECRET]):
            with self.subTest(argument_count=len(args)):
                output, errors = StringIO(), StringIO()
                with redirect_stdout(output), redirect_stderr(errors):
                    result = smoke_demo.main(args)
                self.assertIsInstance(result, int)
                self.assertNotEqual(result, 0)
                self.assertNotIn(SECRET, output.getvalue() + errors.getvalue())


if __name__ == '__main__':
    unittest.main()
