/** Exact, reviewed presentation translations. Never mutate API records or guess a translation.
 * Source quotes and original payloads remain available in their original language.
 */
const ENGLISH: Record<string, string> = {
  "Negosiasi": "Negotiation",
  "Proposal": "Proposal",
  "Demo": "Demo",
  "Discovery": "Discovery",
  "Lead": "Lead",
  "USULAN: E06 mengonfirmasi kriteria \"pengguna serupa\" atas permintaan I0335, lalu meminta account manager memeriksa pengalaman terbaru dan menanyakan kesediaan serta izin kontak Saiyo Group (C06, AM E04) sebelum perkenalan ke Nirwana Hotel & Resto.": "PROPOSAL: E06 confirms the criteria for a similar customer requested in I0335, then asks the account manager to check recent experience and obtain willingness and contact consent from Saiyo Group (C06, AM E04) before introducing them to Nirwana Hotel & Resto.",
  "Kriteria referensi tervalidasi dan minimal satu kandidat menyatakan bersedia serta mengizinkan kontak.": "Reference criteria validated, with at least one candidate willing to participate and consenting to contact.",
  "USULAN: E06 meminta kontak teknis memperkenalkan dan menjadwalkan pertemuan langsung dengan Rina Hapsari (GM Operations, identitas inferensi yang perlu dikonfirmasi); sesuaikan proposal dengan prioritas operasional. Jawab jujur status fitur yang belum rilis dan jangan menjanjikan tanggal fitur tanpa keputusan tercatat.": "PROPOSAL: E06 asks the technical contact to introduce and schedule a direct meeting with Rina Hapsari (GM Operations; inferred identity requiring confirmation). Align the proposal with operational priorities. Be honest about unreleased features and do not promise a release date without a recorded decision.",
  "Pertemuan dengan Rina Hapsari terlaksana, perannya terkonfirmasi, dan kriteria keputusan pengadaan tercatat.": "Meet Rina Hapsari, confirm her role and record the purchasing decision criteria.",
  "USULAN: Jangan menawarkan atau menjanjikan diskon 20% ke Teras Kafe Group sebelum VP Sales memutuskan dan mencatatnya. E07 membawa permintaan tersebut ke VP Sales bersama pembanding preseden. Siapkan opsi tanpa diskon: 15 outlet paket Growth harga normal Rp63.000.000/tahun; pilot sebagian outlet hanya sebagai skenario usulan yang butuh persetujuan. Tanggapi keberatan harga dengan nilai produk berdasar kebutuhan yang tercatat, bukan menyamai harga kompetitor.": "PROPOSAL: Do not offer or promise a 20% discount to Teras Kafe Group before VP Sales decides and records it. E07 brings the request to VP Sales with historical comparisons. Prepare a no-discount option: 15 outlets on Growth at the standard IDR 63,000,000 per year. A partial-outlet pilot is only a proposed scenario requiring approval. Address the price objection through product value based on recorded needs, not by matching the competitor price.",
  "Keputusan VP Sales atas permintaan diskon tercatat di decision_log, lalu tanggapan tertulis pelanggan atas opsi harga yang disetujui.": "Record the VP Sales decision in the decision log, then obtain the customer’s written response to the approved pricing option.",
  "VP Sales (E01): putuskan dan catat di decision_log permintaan diskon 20% (I0348, 2026-09-28); >10% wajib approval. Belum ada keputusan sah yang tercatat untuk DL-002.": "VP Sales (E01) must decide and record the 20% discount request (I0348, 2026-09-28) in the decision log. Discounts above 10% require approval. No valid decision has been recorded for DL-002.",
  "USULAN: E08 mengonfirmasi kriteria \"pengguna serupa\" atas permintaan I0334, lalu meminta account manager memeriksa pengalaman terbaru dan menanyakan kesediaan serta izin kontak Apotek Bunda Sehat (C17, AM E05), Apotek Medika Farma (C09, AM E03), Apotek Kimia Sejahtera (C27, AM E04) sebelum perkenalan ke Klinik Pratama Medika. Kandidat lain dicek belakangan karena catatan: C03 (6 tiket terbuka (3 bug, 1 prioritas Tinggi/Kritis; T0521, T0523, T0526, T0566, T0608, T0616; judul: Laporan tidak sesuai/Selisih transaksi/Sinkronisasi)).": "PROPOSAL: E08 confirms the criteria for a similar customer requested in I0334, then asks the account manager to check recent experience and obtain willingness and contact consent from Apotek Bunda Sehat (C17, AM E05), Apotek Medika Farma (C09, AM E03), and Apotek Kimia Sejahtera (C27, AM E04) before introducing them to Klinik Pratama Medika. Check other candidates later because C03 has 6 open tickets (3 bugs, 1 High/Critical priority; T0521, T0523, T0526, T0566, T0608, T0616; subjects: inaccurate reports / transaction discrepancies / synchronization).",
  "USULAN: E07 menjadwalkan discovery dengan PT Distribusi Sumber Rejeki untuk mengidentifikasi pengambil keputusan, kebutuhan, jumlah outlet dan anggaran sebelum menawarkan harga atau paket.": "PROPOSAL: E07 schedules discovery with PT Distribusi Sumber Rejeki to identify the decision-maker, needs, outlet count and budget before offering a price or package.",
  "Catatan discovery pertama berisi pengambil keputusan, kebutuhan dan jadwal pengadaan.": "A first discovery record covering the decision-maker, needs and purchasing timeline.",
  "Bukti interaksi akun fokus tidak cukup untuk menyimpulkan hambatan; bukan berarti tidak ada risiko.": "There is insufficient interaction evidence to infer blockers; this does not mean no risk.",
  "Kesesuaian, kesediaan dan izin kontak kandidat referensi C06 belum diketahui; kandidat bukan izin.": "Suitability, willingness and contact consent for C06 are unknown; a candidate is not permission.",
  "Kesesuaian, kesediaan dan izin kontak kandidat referensi C17, C09, C27, C03 belum diketahui; kandidat bukan izin.": "Suitability, willingness and contact consent for C17, C09, C27 and C03 are unknown; candidates are not permission.",
  "Tidak ada preseden relevan di candidate_decisions; perbandingan historis terbatas.": "No relevant precedent in candidate_decisions; historical comparison is limited.",
  "Sikap dan kriteria Rina Hapsari terhadap proposal belum tercatat di interaksi.": "Rina Hapsari’s position and criteria for the proposal are not recorded in interactions.",
  "Overlap masa kerja hanya menunjukkan organisasi/periode yang sama; tidak membuktikan saling kenal atau bersedia memberi referensi.": "Overlapping employment shows only a shared organization and period; it does not prove acquaintance or willingness to provide a reference.",
  "Tidak ada interaksi P05 dalam sumber; kebutuhan, hambatan dan pengambil keputusan belum tersedia.": "No P05 interactions exist in the sources; needs, blockers and decision-maker are unknown.",
  "Tidak ada candidate decision melalui penghubung yang tersedia; bukan bukti tidak ada risiko.": "No candidate decision through the available links; this does not mean no risk.",
  "FEAT-07: target terkini belum ditetapkan; tidak ada tanggal rilis pasti dalam sumber.": "FEAT-07: no current target set; the source provides no confirmed release date.",
  "Identitas rina.hapsari@kopilintas.co.id → K017 inferred dari local-part dan riwayat kerja; belum dikonfirmasi langsung.": "The identity rina.hapsari@kopilintas.co.id → K017 is inferred from the email local-part and employment history; not directly confirmed.",
  "Keterkaitan lintas akun dan candidate decisions adalah inferensi pencarian, bukan ranking, rekomendasi atau jaminan berlaku pada deal ini.": "Cross-account links and candidate decisions are retrieval inferences, not rankings, recommendations or guarantees of relevance to this deal.",
  "Champion P01 belum tercatat di CRM; jabatan/peserta meeting bukan bukti champion atau approval.": "No champion recorded for P01; a job title or meeting attendance does not establish a champion or approval.",
  "Tidak ada keputusan/approval tercatat untuk DL-001; permintaan bukan approval.": "No decision or approval recorded for DL-001; a request is not approval.",
  "P01 belum memiliki usage pelanggan sendiri; agregat akun lain hanya konteks referensi. Transaksi server/gejala tidak membuktikan penyebab bug.": "P01 has no customer usage of its own; other accounts provide reference context only. Server transactions or symptoms do not establish a bug’s cause.",
  "Champion P02 belum tercatat di CRM; jabatan/peserta meeting bukan bukti champion atau approval.": "No champion recorded for P02; a job title or meeting attendance does not establish a champion or approval.",
  "Tidak ada keputusan/approval tercatat untuk DL-002; permintaan bukan approval.": "No decision or approval recorded for DL-002; a request is not approval.",
  "P02 belum memiliki usage pelanggan sendiri; agregat akun lain hanya konteks referensi. Transaksi server/gejala tidak membuktikan penyebab bug.": "P02 has no customer usage of its own; other accounts provide reference context only. Server transactions or symptoms do not establish a bug’s cause.",
  "Champion P03 belum tercatat di CRM; jabatan/peserta meeting bukan bukti champion atau approval.": "No champion recorded for P03; a job title or meeting attendance does not establish a champion or approval.",
  "Tidak ada keputusan/approval tercatat untuk DL-003; permintaan bukan approval.": "No decision or approval recorded for DL-003; a request is not approval.",
  "P03 belum memiliki usage pelanggan sendiri; agregat akun lain hanya konteks referensi. Transaksi server/gejala tidak membuktikan penyebab bug.": "P03 has no customer usage of its own; other accounts provide reference context only. Server transactions or symptoms do not establish a bug’s cause.",
  "Champion P04 belum tercatat di CRM; jabatan/peserta meeting bukan bukti champion atau approval.": "No champion recorded for P04; a job title or meeting attendance does not establish a champion or approval.",
  "Tidak ada keputusan/approval tercatat untuk DL-004; permintaan bukan approval.": "No decision or approval recorded for DL-004; a request is not approval.",
  "P04 belum memiliki usage pelanggan sendiri; agregat akun lain hanya konteks referensi. Transaksi server/gejala tidak membuktikan penyebab bug.": "P04 has no customer usage of its own; other accounts provide reference context only. Server transactions or symptoms do not establish a bug’s cause.",
  "Champion P05 belum tercatat di CRM; jabatan/peserta meeting bukan bukti champion atau approval.": "No champion recorded for P05; a job title or meeting attendance does not establish a champion or approval.",
  "Tidak ada keputusan/approval tercatat untuk DL-005; permintaan bukan approval.": "No decision or approval recorded for DL-005; a request is not approval.",
  "P05 belum memiliki usage pelanggan sendiri; agregat akun lain hanya konteks referensi. Transaksi server/gejala tidak membuktikan penyebab bug.": "P05 has no customer usage of its own; other accounts provide reference context only. Server transactions or symptoms do not establish a bug’s cause.",
  "D-2024-01: bukti_interaction_id kosong; bukti hanya log keputusan, bukan email rekaan.": "D-2024-01: no interaction reference; evidence is the decision log only, not an invented email.",
  "D-2024-05: bukti_interaction_id kosong; bukti hanya log keputusan, bukan email rekaan.": "D-2024-05: no interaction reference; evidence is the decision log only, not an invented email.",
  "D-2025-08: bukti_interaction_id kosong; bukti hanya log keputusan, bukan email rekaan.": "D-2025-08: no interaction reference; evidence is the decision log only, not an invented email.",
  "D-2025-12: bukti_interaction_id kosong; bukti hanya log keputusan, bukan email rekaan.": "D-2025-12: no interaction reference; evidence is the decision log only, not an invented email.",
  "D-2026-08: bukti_interaction_id kosong; bukti hanya log keputusan, bukan email rekaan.": "D-2026-08: no interaction reference; evidence is the decision log only, not an invented email.",
  "D-2024-02: bukti_interaction_id kosong; bukti hanya log keputusan, bukan email rekaan.": "D-2024-02: no interaction reference; evidence is the decision log only, not an invented email.",
  "D-2024-06: bukti_interaction_id kosong; bukti hanya log keputusan, bukan email rekaan.": "D-2024-06: no interaction reference; evidence is the decision log only, not an invented email.",
  "D-2024-07: bukti_interaction_id kosong; bukti hanya log keputusan, bukan email rekaan.": "D-2024-07: no interaction reference; evidence is the decision log only, not an invented email.",
  "D-2025-02: bukti_interaction_id kosong; bukti hanya log keputusan, bukan email rekaan.": "D-2025-02: no interaction reference; evidence is the decision log only, not an invented email.",
  "D-2025-04: bukti_interaction_id kosong; bukti hanya log keputusan, bukan email rekaan.": "D-2025-04: no interaction reference; evidence is the decision log only, not an invented email.",
  "D-2025-06: bukti_interaction_id kosong; bukti hanya log keputusan, bukan email rekaan.": "D-2025-06: no interaction reference; evidence is the decision log only, not an invented email.",
  "D-2025-07: bukti_interaction_id kosong; bukti hanya log keputusan, bukan email rekaan.": "D-2025-07: no interaction reference; evidence is the decision log only, not an invented email.",
  "D-2026-04: bukti_interaction_id kosong; bukti hanya log keputusan, bukan email rekaan.": "D-2026-04: no interaction reference; evidence is the decision log only, not an invented email.",
  "D-2026-09: bukti_interaction_id kosong; bukti hanya log keputusan, bukan email rekaan.": "D-2026-09: no interaction reference; evidence is the decision log only, not an invented email.",
  "D-2026-11: bukti_interaction_id kosong; bukti hanya log keputusan, bukan email rekaan.": "D-2026-11: no interaction reference; evidence is the decision log only, not an invented email.",
  "D-2026-06: bukti_interaction_id kosong; bukti hanya log keputusan, bukan email rekaan.": "D-2026-06: no interaction reference; evidence is the decision log only, not an invented email."
};
const CATALOG: Record<string, string> = {
  "2 preseden decision_log relevan (D-2025-11, D-2026-08) = 1/1 poin; preseden bukan izin otomatis.": "2 relevant decision_log precedents (D-2025-11, D-2026-08) = 1/1 point; precedents do not automatically grant permission.",
  "5 preseden decision_log relevan (D-2024-02, D-2025-02, D-2025-06, D-2025-12, D-2026-04) = 1/1 poin; preseden bukan izin otomatis.": "5 relevant decision_log precedents (D-2024-02, D-2025-02, D-2025-06, D-2025-12, D-2026-04) = 1/1 point; precedents do not automatically grant permission.",
  ">= 1 preseden decision_log dengan fit cocok/sebagian: 1; lainnya 0": "At least 1 matching or partially matching decision_log precedent: 1; otherwise 0",
  ">= Rp200.000.000: 3; >= Rp100.000.000: 2; >= Rp50.000.000: 1; lainnya 0": ">= Rp200.000.000: 3; >= Rp100.000.000: 2; >= Rp50.000.000: 1; otherwise 0",
  "Aktivitas yang tidak dicatat di dataset tidak dapat disimpulkan ada atau tidak ada.": "The dataset cannot establish whether unrecorded activity took place.",
  "Analisis bisnis per deal: analyze_deal_trace(context, mode='rules', diagnostic) menghasilkan Recommendation v1, status bukti, hambatan, approval/izin dan preseden. Jev tidak dipakai.": "Per-deal business analysis: analyze_deal_trace(context, mode='rules', diagnostic) returns Recommendation v1, evidence status, blockers, approval/consent requirements and precedents. Jev is not used.",
  "Approval VP Sales masih tertunda; rank tidak mengesahkan diskon atau penawaran.": "VP Sales approval is still pending; priority does not authorize a discount or offer.",
  "Approval/izin adalah gate dari analisis rules; nilai besar atau preseden sukses tidak menghapus gate.": "Approval and consent are requirements from the rules analysis; high value or successful precedents do not remove them.",
  "Batas anggaran dan perbandingan cakupan penawaran belum dikonfirmasi.": "The budget ceiling and comparable offer scope have not been confirmed.",
  "Belum ada hambatan bersumber dari akun fokus: unknown, 0 poin, bukan bukti negatif. Tier discovery: tidak dipakai menghitung skor.": "No blocker supported by sources for this account: unknown, 0 points, not negative evidence. Discovery tier: excluded from scoring.",
  "Bobot dan bin adalah pilihan desain yang dapat diperdebatkan; belum divalidasi terhadap hasil closing historis.": "Weights and bands are design choices open to discussion; they have not been validated against historical closing outcomes.",
  "Bukti terbatas pada konteks dan diagnostic snapshot; ketiadaan record bukan bukti tidak ada aktivitas.": "Evidence is limited to the context and diagnostic snapshot; a missing record does not prove there was no activity.",
  "Butuh modul apotek untuk 9 klinik. Bu Ratna minta referensi pelanggan apotek yang sudah memakai KasirNusa.": "A pharmacy module is needed for 9 clinics. Ms Ratna requests a reference from a pharmacy customer already using KasirNusa.",
  "Deal discovery ditempatkan setelah acceleration karena bukti belum cukup untuk dibandingkan; bukan peluang buruk.": "Discovery deals follow acceleration deals because evidence is insufficient for comparison, not because they are poor opportunities.",
  "Di atas DL-001 (skor 8): skor sama; diputus tie-break 1 hambatan dinyatakan pelanggan (2 vs 1).": "Above DL-001 (score 8): equal scores; decided by tie-break 1, customer-stated blocker (2 vs 1).",
  "Di atas DL-002 (skor 5): selisih 3 poin (tahap 3 vs 2, nilai 3 vs 1).": "Above DL-002 (score 5): 3-point difference (stage 3 vs 2, value 3 vs 1).",
  "Di atas DL-003 (skor 2): selisih 3 poin (tahap 2 vs 1, nilai 1 vs 0, preseden 1 vs 0).": "Above DL-003 (score 2): 3-point difference (stage 2 vs 1, value 1 vs 0, precedent 1 vs 0).",
  "Di atas deal discovery DL-005 karena hambatan deal ini sudah bersumber; bukan karena deal discovery dinilai buruk.": "Above discovery deal DL-005 because this deal has a sourced blocker, not because the discovery deal is considered poor.",
  "Di bawah DL-001 (skor 8): selisih 3 poin (tahap 3 vs 2, nilai 3 vs 1).": "Below DL-001 (score 8): 3-point difference (stage 3 vs 2, value 3 vs 1).",
  "Di bawah DL-002 (skor 5): selisih 3 poin (tahap 2 vs 1, nilai 1 vs 0, preseden 1 vs 0).": "Below DL-002 (score 5): 3-point difference (stage 2 vs 1, value 1 vs 0, precedent 1 vs 0).",
  "Di bawah DL-004 (skor 8): skor sama; diputus tie-break 1 hambatan dinyatakan pelanggan (2 vs 1).": "Below DL-004 (score 8): equal scores; decided by tie-break 1, customer-stated blocker (2 vs 1).",
  "Discovery diurutkan nilai potensi menurun lalu tahap, sebagai urutan jadwal discovery tanpa skor.": "Discovery is scheduled by descending potential value, then stage, without a score.",
  "FAKTA | D-2024-02 (2024-04-03, diskon, akun C15): 20% -> Ditolak oleh E01; alasan: Di luar kebijakan; ditawarkan 10%": "FACT | D-2024-02 (2024-04-03, discount, account C15): 20% -> Rejected by E01; reason: Outside policy; 10% offered",
  "FAKTA | D-2025-02 (2025-03-04, diskon, akun C23): 20% -> Ditolak oleh E01; alasan: Di atas batas 15%; menyamai harga kompetitor merusak harga pasar. Deal kemudian kalah karena harga.": "FACT | D-2025-02 (2025-03-04, discount, account C23): 20% -> Rejected by E01; reason: Above the 15% limit; matching competitor prices harms market pricing. The deal was later lost on price.",
  "FAKTA | D-2025-06 (2025-08-12, pengecualian, akun C23): Paket Starter tanpa diskon, pilot 6 outlet -> Disetujui oleh E01; alasan: Pendekatan alternatif setelah kalah Maret: mulai dari Starter, naik paket bila puas. Deal menang Sep 2025.": "FACT | D-2025-06 (2025-08-12, exception, account C23): Starter plan without a discount, 6-outlet pilot -> Approved by E01; reason: An alternative after the March loss: start on Starter and upgrade if satisfied. The deal was won in Sep 2025.",
  "FAKTA | D-2025-11 (2025-11-28, diskon, akun C01): 15% -> Disetujui oleh E01; alasan: Pengecualian: akun strategis 42 outlet; komitmen integrasi akuntansi rilis Q3 2026": "FACT | D-2025-11 (2025-11-28, discount, account C01): 15% -> Approved by E01; reason: Exception for a strategic account with 42 outlets; commitment to release accounting integration in Q3 2026",
  "FAKTA | D-2025-11: janji fitur FEAT-07 berstatus 'Belum ditepati'.": "FACT | D-2025-11: the FEAT-07 feature promise is marked 'Not fulfilled'.",
  "FAKTA | D-2025-12 (2025-12-09, diskon, akun C33): 18% -> Ditolak oleh E01; alasan: Volume kecil": "FACT | D-2025-12 (2025-12-09, discount, account C33): 18% -> Rejected by E01; reason: Small volume",
  "FAKTA | D-2026-04 (2026-03-26, diskon, akun C21): 20% -> Ditolak oleh E01; alasan: Di luar kebijakan; ditawarkan Starter": "FACT | D-2026-04 (2026-03-26, discount, account C21): 20% -> Rejected by E01; reason: Outside policy; Starter offered",
  "FAKTA | D-2026-08 (2026-07-14, eskalasi, akun C01): Kepastian jadwal FEAT-07 -> Menunggu oleh E09; alasan: Klien menanyakan jadwal integrasi; belum ada tanggal dari produk": "FACT | D-2026-08 (2026-07-14, escalation, account C01): Confirm the FEAT-07 schedule -> Pending with E09; reason: The client asked about the integration schedule; no date from product yet",
  "FAKTA | DL-001 Grup Ritel Mandala: stage Proposal sejak 2026-09-11 (20 hari per 2026-10-01); nilai potensi tahunan Rp252.000.000 (bukan pendapatan).": "FACT | DL-001 Grup Ritel Mandala: Proposal stage since 2026-09-11 (20 days as of 2026-10-01); potential annual value Rp252.000.000 (not revenue).",
  "FAKTA | DL-002 Teras Kafe Group: stage Demo sejak 2026-08-17 (45 hari per 2026-10-01); nilai potensi tahunan Rp63.000.000 (bukan pendapatan); kompetitor tercatat: KasirPro.": "FACT | DL-002 Teras Kafe Group: Demo stage since 2026-08-17 (45 days as of 2026-10-01); potential annual value Rp63.000.000 (not revenue); recorded competitor: KasirPro.",
  "FAKTA | DL-003 Klinik Pratama Medika: stage Discovery sejak 2026-09-21 (10 hari per 2026-10-01); nilai potensi tahunan Rp37.800.000 (bukan pendapatan).": "FACT | DL-003 Klinik Pratama Medika: Discovery stage since 2026-09-21 (10 days as of 2026-10-01); potential annual value Rp37.800.000 (not revenue).",
  "FAKTA | DL-004 Nirwana Hotel & Resto: stage Negosiasi sejak 2026-09-01 (30 hari per 2026-10-01); nilai potensi tahunan Rp147.000.000 (bukan pendapatan).": "FACT | DL-004 Nirwana Hotel & Resto: Negotiation stage since 2026-09-01 (30 days as of 2026-10-01); potential annual value Rp147.000.000 (not revenue).",
  "FAKTA | DL-005 PT Distribusi Sumber Rejeki: stage Lead sejak 2026-09-26 (5 hari per 2026-10-01); nilai potensi tahunan Rp168.000.000 (bukan pendapatan).": "FACT | DL-005 PT Distribusi Sumber Rejeki: Lead stage since 2026-09-26 (5 days as of 2026-10-01); potential annual value Rp168.000.000 (not revenue).",
  "FAKTA | Deal preseden DL-006 juga mencatat kompetitor KasirPro (crm_deals.kompetitor).": "FACT | Precedent deal DL-006 also records competitor KasirPro (crm_deals.kompetitor).",
  "FAKTA | Deal preseden DL-007 juga mencatat kompetitor KasirPro (crm_deals.kompetitor).": "FACT | Precedent deal DL-007 also records competitor KasirPro (crm_deals.kompetitor).",
  "FAKTA | Di candidate_decisions konteks ini ada 6 keputusan diskon >10%: 1 disetujui (D-2025-11), 5 ditolak (D-2024-02, D-2024-06, D-2025-02, D-2025-12, D-2026-04).": "FACT | This context's candidate_decisions contain 6 decisions on discounts >10%: 1 approved (D-2025-11), 5 rejected (D-2024-02, D-2024-06, D-2025-02, D-2025-12, D-2026-04).",
  "FAKTA | Hitungan: 15 outlet x Rp350.000 x 12 = Rp63.000.000; diskon 20% -> Rp50.400.000 (berkurang Rp12.600.000).": "FACT | Calculation: 15 outlets x Rp350.000 x 12 = Rp63.000.000; 20% discount -> Rp50.400.000 (reduction of Rp12.600.000).",
  "FAKTA | I0269 (2026-07-30, P02): \"15 kafe di Malang dan Batu. Butuh POS dan stok bahan baku.\"": "FACT | I0269 (2026-07-30, P02), translated: \"15 cafes in Malang and Batu. POS and raw-material inventory are needed.\"",
  "FAKTA | I0296 (2026-08-17, P02): \"Pak Teddy suka produknya tetapi menilai harga terlalu tinggi. KasirPro menawarkan harga sekitar 20% lebih murah.\"": "FACT | I0296 (2026-08-17, P02), translated: \"Mr Teddy likes the product but considers the price too high. KasirPro offers a price around 20% lower.\"",
  "FAKTA | I0296: kompetitor disebut ~20% lebih murah (klaim, belum diverifikasi).": "FACT | I0296: the competitor is described as ~20% cheaper (unverified claim).",
  "FAKTA | I0334 (2026-09-21, P03): \"Butuh modul apotek untuk 9 klinik. Bu Ratna minta referensi pelanggan apotek yang sudah memakai KasirNusa.\"": "FACT | I0334 (2026-09-21, P03), translated: \"A pharmacy module is needed for 9 clinics. Ms Ratna requests a reference from a pharmacy customer already using KasirNusa.\"",
  "FAKTA | I0335 (2026-09-22, P04): \"Pak Bagus, Direktur Utama kami minta rekomendasi dari pengguna yang mirip dengan kami sebelum tanda tangan. Kami tunda dulu sampai ada referensi.\"": "FACT | I0335 (2026-09-22, P04), translated: \"Mr Bagus, our President Director wants a recommendation from a similar user before signing. We are putting this on hold until there is a reference.\"",
  "FAKTA | I0343 (2026-09-24, P01): \"Mas Bagus, proposal sudah saya teruskan ke GM Operations yang baru bergabung awal September. Keputusan pengadaan sistem kasir ada di beliau, saya hanya menilai sisi teknis.\"": "FACT | I0343 (2026-09-24, P01), translated: \"Bagus, I have forwarded the proposal to the GM Operations who joined in early September. The POS procurement decision is theirs; I only assess the technical side.\"",
  "FAKTA | I0348 (2026-09-28): PERMINTAAN diskon 20% (permintaan, bukan approval).": "FACT | I0348 (2026-09-28): REQUEST for a 20% discount (a request, not approval).",
  "FAKTA | I0348 (2026-09-28, P02): \"Pak Andi, untuk menutup Teras Kafe saya usul diskon 20% agar menyamai KasirPro. Mohon keputusan.\"": "FACT | I0348 (2026-09-28, P02), translated: \"Mr Andi, to close Teras Kafe I propose a 20% discount to match KasirPro. Please make a decision.\"",
  "FAKTA | K017 sebelumnya Head of Operations di Kopi Lintas Nusantara (2021-03-01 s.d. 2026-08-15).": "FACT | K017 was previously Head of Operations at Kopi Lintas Nusantara (2021-03-01 to 2026-08-15).",
  "FAKTA | K017 sebelumnya Operations Supervisor di PT Kreasi Kuliner (2016-06-01 s.d. 2021-02-28).": "FACT | K017 was previously Operations Supervisor at PT Kreasi Kuliner (2016-06-01 to 2021-02-28).",
  "FAKTA | Kandidat C03 Apotek Sehat Sentosa (urutan cek 4, cek_dengan_catatan): relasi feature_usage, shared_industry; Apotek, 18 outlet; health dashboard Kuning, NPS 8; usage FEAT-05 2026-09: 14 pengguna aktif.": "FACT | Candidate C03 Apotek Sehat Sentosa (check order 4, check with reservations): feature_usage and shared_industry relationships; pharmacy, 18 outlets; dashboard health Yellow, NPS 8; FEAT-05 usage in 2026-09: 14 active users.",
  "FAKTA | Kandidat C06 Saiyo Group (urutan cek 1, cek_pertama): relasi work_overlap; Resto Padang, 30 outlet; health dashboard Hijau, NPS 9.": "FACT | Candidate C06 Saiyo Group (check order 1, check first): work_overlap relationship; Padang restaurant, 30 outlets; dashboard health Green, NPS 9.",
  "FAKTA | Kandidat C09 Apotek Medika Farma (urutan cek 2, cek_pertama): relasi feature_usage, shared_industry; Apotek, 15 outlet; health dashboard Hijau, NPS 9; usage FEAT-05 2026-09: 11 pengguna aktif.": "FACT | Candidate C09 Apotek Medika Farma (check order 2, check first): feature_usage and shared_industry relationships; pharmacy, 15 outlets; dashboard health Green, NPS 9; FEAT-05 usage in 2026-09: 11 active users.",
  "FAKTA | Kandidat C17 Apotek Bunda Sehat (urutan cek 1, cek_pertama): relasi feature_usage, shared_industry; Apotek, 10 outlet; health dashboard Hijau, NPS 10; usage FEAT-05 2026-09: 22 pengguna aktif.": "FACT | Candidate C17 Apotek Bunda Sehat (check order 1, check first): feature_usage and shared_industry relationships; pharmacy, 10 outlets; dashboard health Green, NPS 10; FEAT-05 usage in 2026-09: 22 active users.",
  "FAKTA | Kandidat C27 Apotek Kimia Sejahtera (urutan cek 3, cek_pertama): relasi feature_usage, shared_industry; Apotek, 22 outlet; health dashboard Kuning, NPS 8; usage FEAT-05 2026-09: 48 pengguna aktif.": "FACT | Candidate C27 Apotek Kimia Sejahtera (check order 3, check first): feature_usage and shared_industry relationships; pharmacy, 22 outlets; dashboard health Yellow, NPS 8; FEAT-05 usage in 2026-09: 48 active users.",
  "FAKTA | Verifikasi Bima discount_request:DL-002:I0348:20: pencarian 30 record decision_log menemukan 0 log untuk P02/DL-002.": "FACT | Bima verification discount_request:DL-002:I0348:20: searching 30 decision_log records found 0 logs for P02/DL-002.",
  "FAKTA | Verifikasi kewenangan Bima (DL-001:authority:I0343) menunjuk kandidat yang sama: K017 (tetap inferred).": "FACT | Bima's authority verification (DL-001:authority:I0343) identifies the same candidate: K017 (still inferred).",
  "Faktor hambatan_dinyatakan_pelanggan unknown; tidak diberi poin dan bukan bukti negatif.": "Customer-stated blocker is unknown; no points assigned, not negative evidence.",
  "Faktor unknown = 0 poin dan dicatat; limitations menyebut rank yang dapat berubah bila unknown terisi.": "Unknown factors receive 0 points and are recorded; limitations identify rankings that could change if the information becomes available.",
  "Gate tetap berlaku terlepas dari rank: VP Sales (E01): putuskan dan catat di decision_log permintaan diskon 20% (I0348, 2026-09-28); >10% wajib approval. Belum ada keputusan sah yang tercatat untuk DL-002.": "The requirement applies regardless of rank: VP Sales (E01) must decide and record the 20% discount request (I0348, 2026-09-28) in decision_log; discounts >10% require approval. No valid decision is recorded for DL-002.",
  "Gate wajib sebelum tindakan; tidak menaikkan/menurunkan skor dan tidak dihapus oleh nilai atau preseden.": "Required before acting; does not increase or decrease the score and is not removed by value or precedents.",
  "Hambatan dinyatakan pelanggan dideteksi dengan aturan leksikal pada isi pesan; parafrase dapat terlewat.": "Customer-stated blockers are detected using lexical rules on message content; paraphrases may be missed.",
  "Hambatan yang dinyatakan pelanggan memberi tindakan pembuka yang jelas.": "A customer-stated blocker provides a clear first action.",
  "I0296 (2026-08-17): Pak Teddy suka produknya tetapi menilai harga terlalu tinggi. KasirPro menawarkan harga sekitar 20% lebih murah.": "I0296 (2026-08-17), translated: Mr Teddy likes the product but considers the price too high. KasirPro offers a price around 20% lower.",
  "I0334 (2026-09-21): Butuh modul apotek untuk 9 klinik. Bu Ratna minta referensi pelanggan apotek yang sudah memakai KasirNusa.": "I0334 (2026-09-21), translated: A pharmacy module is needed for 9 clinics. Ms Ratna requests a reference from a pharmacy customer already using KasirNusa.",
  "I0335 (2026-09-22): Pak Bagus, Direktur Utama kami minta rekomendasi dari pengguna yang mirip dengan kami sebelum tanda tangan. Kami tunda dulu sampai ada referensi.": "I0335 (2026-09-22), translated: Mr Bagus, our President Director wants a recommendation from a similar user before signing. We are putting this on hold until there is a reference.",
  "I0343 mencatat pesan pelanggan: Mas Bagus, proposal sudah saya teruskan ke GM Operations yang baru bergabung awal September. Keputusan pengadaan sistem kasir ada di beliau, saya hanya menilai sisi teknis. CRM mencatat Rina Hapsari (K017) sebagai GM Operations di P01; riwayat cocok pada tanggal pesan.": "I0343 records a customer message, translated: Bagus, I have forwarded the proposal to the GM Operations who joined in early September. The POS procurement decision is theirs; I only assess the technical side. CRM lists Rina Hapsari (K017) as GM Operations at P01; the employment history matches the message date.",
  "I0348 (2026-09-28) email internal: Pak Andi, untuk menutup Teras Kafe saya usul diskon 20% agar menyamai KasirPro. Mohon keputusan. Pencarian log pada snapshot menemukan 0 keputusan dengan account_id dan deal_id fokus.": "I0348 (2026-09-28), internal email, translated: Mr Andi, to close Teras Kafe I propose a 20% discount to match KasirPro. Please make a decision. The snapshot log search found 0 decisions matching the account_id and deal_id in focus.",
  "INTERPRETASI | C03 catatan: health dashboard Kuning (indikator CRM, bisa tidak mutakhir).": "INTERPRETATION | C03 note: dashboard health Yellow (a CRM indicator that may be outdated).",
  "INTERPRETASI | C03 dicek belakangan: 6 tiket terbuka (3 bug, 1 prioritas Tinggi/Kritis; T0521, T0523, T0526, T0566, T0608, T0616; judul: Laporan tidak sesuai/Selisih transaksi/Sinkronisasi).": "INTERPRETATION | Check C03 later: 6 open tickets (3 bugs, 1 High/Critical priority; T0521, T0523, T0526, T0566, T0608, T0616; subjects: inaccurate reports / transaction discrepancies / synchronization).",
  "INTERPRETASI | C06 catatan: 1 tiket terbuka (0 bug, 0 prioritas Tinggi/Kritis; T0637; judul: Laci kasir tidak terbuka).": "INTERPRETATION | C06 note: 1 open ticket (0 bugs, 0 High/Critical priority; T0637; subject: cash drawer does not open).",
  "INTERPRETASI | C06 catatan: industri Resto Padang berbeda dari Hospitality; kemiripan perlu dicek.": "INTERPRETATION | C06 note: the Padang restaurant industry differs from Hospitality; similarity needs checking.",
  "INTERPRETASI | C06: overlap masa kerja K028 Hartono Gunawan (Direktur Utama) dan K116 Budi Santoso (CFO) di PT Sentosa Abadi Group (2015-02-01 s.d. 2019-11-30); overlap tidak membuktikan saling kenal (acquaintance belum dikonfirmasi).": "INTERPRETATION | C06: K028 Hartono Gunawan (President Director) and K116 Budi Santoso (CFO) had overlapping employment at PT Sentosa Abadi Group (2015-02-01 to 2019-11-30); overlap does not prove they know each other (acquaintance unconfirmed).",
  "INTERPRETASI | C27 catatan: health dashboard Kuning (indikator CRM, bisa tidak mutakhir).": "INTERPRETATION | C27 note: dashboard health Yellow (a CRM indicator that may be outdated).",
  "INTERPRETASI | C27: riwayat eskalasi D-2025-08: Bug struk ganda (BUG-398) (Disetujui).": "INTERPRETATION | C27: escalation history D-2025-08: Duplicate receipt bug (BUG-398) (Approved).",
  "INTERPRETASI | Diperiksa tetapi tidak cocok untuk hambatan ini: D-2024-01, D-2024-05, D-2025-08, D-2025-12.": "INTERPRETATION | Checked but not relevant to this blocker: D-2024-01, D-2024-05, D-2025-08, D-2025-12.",
  "INTERPRETASI | Diperiksa tetapi tidak cocok untuk hambatan ini: D-2024-05, D-2025-08, D-2026-06.": "INTERPRETATION | Checked but not relevant to this blocker: D-2024-05, D-2025-08, D-2026-06.",
  "INTERPRETASI | Diperiksa tetapi tidak cocok untuk hambatan ini: D-2024-06, D-2024-07, D-2025-04, D-2025-07, D-2025-11, D-2026-08, D-2026-09, D-2026-11.": "INTERPRETATION | Checked but not relevant to this blocker: D-2024-06, D-2024-07, D-2025-04, D-2025-07, D-2025-11, D-2026-08, D-2026-09, D-2026-11.",
  "INTERPRETASI | INFERENSI: I0343 menyebut \"GM Operations\" sebagai pemegang keputusan; satu-satunya kontak CRM P01 dengan jabatan itu adalah K017 Rina Hapsari (mulai 2026-09-01). Belum dikonfirmasi langsung.": "INTERPRETATION | INFERENCE: I0343 identifies \"GM Operations\" as the decision-maker; the only P01 CRM contact with that role is K017 Rina Hapsari (since 2026-09-01). Not directly confirmed.",
  "INTERPRETASI | Kandidat related_account_* adalah hasil pencarian bersumber; urutan cek bukan penilaian kelayakan. Kesesuaian, kesediaan menjadi referensi dan izin kontak belum diketahui (null).": "INTERPRETATION | related_account_* candidates are retrieved from sources; check order is not a suitability assessment. Suitability, willingness to give a reference and contact consent are unknown (null).",
  "INTERPRETASI | Risiko kepercayaan: D-2025-11 di C01 (FEAT-07; Belum ditepati). Rina Hapsari mungkin mengetahui pengalaman ini (inferensi dari riwayat kerja, belum dikonfirmasi).": "INTERPRETATION | Trust risk: D-2025-11 at C01 (FEAT-07; Not fulfilled). Rina Hapsari may know about this experience (inferred from employment history, unconfirmed).",
  "INTERPRETASI | Risiko kepercayaan: D-2026-08 di C01 (Kepastian jadwal FEAT-07; Menunggu). Rina Hapsari mungkin mengetahui pengalaman ini (inferensi dari riwayat kerja, belum dikonfirmasi).": "INTERPRETATION | Trust risk: D-2026-08 at C01 (Confirm FEAT-07 schedule; Pending). Rina Hapsari may know about this experience (inferred from employment history, unconfirmed).",
  "INTERPRETASI | [cocok] Alasan D-2025-02 menyebut batas 15%; ini catatan satu keputusan, bukan aturan universal. Aturan tertulis: diskon >10% butuh VP Sales.": "INTERPRETATION | [matching] D-2025-02 mentions a 15% limit; this is one decision record, not a universal rule. Written policy: discounts >10% require VP Sales.",
  "INTERPRETASI | [cocok] Permintaan 20% pada deal ini sama dengan D-2025-02 yang ditolak; preseden ini tidak mendukung asumsi bahwa permintaan sekarang akan disetujui; keputusan tetap wewenang VP Sales.": "INTERPRETATION | [matching] This deal's 20% request matches the rejected D-2025-02 request; the precedent does not support assuming approval now. The decision remains with VP Sales.",
  "INTERPRETASI | [sebagian] D-2025-06 adalah pengecualian yang diputuskan; satu keberhasilan lama bukan jaminan.": "INTERPRETATION | [partial] D-2025-06 is a decided exception; one past success is not a guarantee.",
  "INTERPRETASI | [sebagian] D-2025-11 di C01 masih terbuka (Belum ditepati); relevan sebagai risiko kepercayaan karena terkait riwayat kerja pengambil keputusan (inferensi), bukan pola harga.": "INTERPRETATION | [partial] D-2025-11 at C01 is still open (Not fulfilled); relevant as a trust risk linked to the decision-maker's employment history (inference), not a pricing pattern.",
  "INTERPRETASI | [sebagian] D-2025-12: diskon 18% (>10%) ditolak; berbeda dari permintaan [20]%.": "INTERPRETATION | [partial] D-2025-12: an 18% discount (>10%) was rejected; different from the [20]% request.",
  "INTERPRETASI | [sebagian] D-2026-08 di C01 masih terbuka (Menunggu); relevan sebagai risiko kepercayaan karena terkait riwayat kerja pengambil keputusan (inferensi), bukan pola harga.": "INTERPRETATION | [partial] D-2026-08 at C01 is still open (Pending); relevant as a trust risk linked to the decision-maker's employment history (inference), not a pricing pattern.",
  "INTERPRETASI | [sebagian] Paket Starter (maks 10 outlet) TIDAK dapat langsung menampung 15 outlet deal ini. Meniru D-2025-06 berarti pilot sebagian outlet: usulan skenario, belum disetujui pelanggan maupun VP Sales.": "INTERPRETATION | [partial] Starter (maximum 10 outlets) CANNOT directly cover this deal's 15 outlets. Reusing D-2025-06 means a partial-outlet pilot: a proposed scenario, not approved by the customer or VP Sales.",
  "INTERPRETASI | [sebagian] Permintaan 20% pada deal ini sama dengan D-2024-02 yang ditolak; preseden ini tidak mendukung asumsi bahwa permintaan sekarang akan disetujui; keputusan tetap wewenang VP Sales.": "INTERPRETATION | [partial] This deal's 20% request matches the rejected D-2024-02 request; the precedent does not support assuming approval now. The decision remains with VP Sales.",
  "INTERPRETASI | [sebagian] Permintaan 20% pada deal ini sama dengan D-2026-04 yang ditolak; preseden ini tidak mendukung asumsi bahwa permintaan sekarang akan disetujui; keputusan tetap wewenang VP Sales.": "INTERPRETATION | [partial] This deal's 20% request matches the rejected D-2026-04 request; the precedent does not support assuming approval now. The decision remains with VP Sales.",
  "Identitas email historis inferred dari graph belum dikonfirmasi langsung.": "The historical email identity inferred from the graph has not been directly confirmed.",
  "Identitas pengambil keputusan K017 masih inferred dan perlu dikonfirmasi langsung.": "Decision-maker identity K017 is still inferred and requires direct confirmation.",
  "Implikasi tindak lanjut adalah pemeriksaan informasi, bukan Recommendation Ical, approval, ranking atau confidence.": "Follow-up implications are information checks, not Ical's Recommendation, approval, ranking or confidence.",
  "Interaksi eksternal mencakup email keluar dan catatan meeting; tanggal terakhir bukan otomatis tanggal balasan pelanggan.": "External interactions include outbound email and meeting notes; the last date is not necessarily a customer reply date.",
  "Jumlah poin 2/10; dipakai untuk urutan dalam tier acceleration. Bukan probabilitas closing.": "Total 2/10 points; used to order the acceleration tier. Not a closing probability.",
  "Jumlah poin 5/10; dipakai untuk urutan dalam tier acceleration. Bukan probabilitas closing.": "Total 5/10 points; used to order the acceleration tier. Not a closing probability.",
  "Jumlah poin 8/10; dipakai untuk urutan dalam tier acceleration. Bukan probabilitas closing.": "Total 8/10 points; used to order the acceleration tier. Not a closing probability.",
  "Kandidat referensi adalah hasil pencarian bersumber, bukan izin; kesesuaian, kesediaan dan izin kontak masih null. Overlap kerja tidak membuktikan saling kenal.": "Reference candidates are source-based search results, not permission; suitability, willingness and contact consent remain null. Employment overlap does not establish acquaintance.",
  "Kebutuhan, hambatan, proses pengadaan, pengambil keputusan dan kontak pelanggan belum cukup didukung percakapan.": "Conversations do not sufficiently support the needs, blockers, purchasing process, decision-maker or customer contacts.",
  "Kekurangan percakapan adalah batas pengetahuan, bukan bukti deal kalah, tidak berminat, atau outlier statistik.": "Missing conversation limits what is known; it is not evidence of a lost deal, lack of interest or a statistical outlier.",
  "Kelayakan, pengalaman terkini, serta izin kandidat untuk berbagi pengalaman belum dikonfirmasi.": "Suitability, recent experience and the candidate's permission to share their experience are unconfirmed.",
  "Keputusan atas permintaan dan justifikasi komersial perlu dikonfirmasi; tidak disimpulkan dari email permintaan.": "The decision on the request and its commercial justification require confirmation; they cannot be inferred from the request email.",
  "Kesediaan memberi referensi dan persetujuan untuk dihubungi belum tersedia.": "Willingness to provide a reference and consent to be contacted are unavailable.",
  "Kesesuaian kandidat dengan kebutuhan prospek belum dikonfirmasi.": "The candidate's fit with the prospect's needs is unconfirmed.",
  "Klarifikasi anggaran dan lingkup pembandingan kepada pelanggan; jangan menganggap angka kompetitor sebagai diskon yang disetujui.": "Clarify the budget and comparison scope with the customer; do not treat competitor pricing as an approved discount.",
  "Konfirmasi langsung identitas dan wewenang pengadaan dari pelanggan belum tersedia.": "Direct customer confirmation of identity and purchasing authority is unavailable.",
  "Konfirmasikan siapa pemegang wewenang pengadaan dan jalur komunikasi langsung sebelum meneruskan proposal.": "Confirm the purchasing decision-maker and direct communication route before forwarding the proposal.",
  "Konteks saja: tanggal interaksi eksternal terakhir (termasuk outbound sales, bukan bukti balasan pembeli); null = tidak ada dalam cakupan sumber.": "Context only: last external interaction date (including outbound sales, not proof of a buyer reply); null means unavailable in the source scope.",
  "Konteks saja: umur tahap tidak dibandingkan lintas tahap (bukan SLA/outlier; statistik not_assessed).": "Context only: stage age is not compared across stages (not an SLA or outlier; statistics not_assessed).",
  "Konteks tidak dihitung: umur tahap, interaksi eksternal terakhir, gate approval/izin.": "Not scored: stage age, last external interaction and approval/consent requirements.",
  "Kriteria pengguna yang dianggap mirip dan format referensi yang diterima belum lengkap.": "Criteria for a similar user and the accepted reference format are incomplete.",
  "Lamanya tahap tidak membuktikan harga sebagai satu-satunya penyebab.": "Time in stage does not prove that price is the only cause.",
  "Lead 0, Discovery 1, Demo 2, Proposal 3, Negosiasi 4 (crm_deals.stage)": "Lead 0, Discovery 1, Demo 2, Proposal 3, Negotiation 4 (crm_deals.stage)",
  "Lengkapi discovery dan pencatatan kontak/interaksi terlebih dahulu; jangan memberi diagnosis komersial dari kekosongan sumber.": "Complete discovery and contact/interaction records first; do not infer a commercial diagnosis from missing sources.",
  "Menentukan tier: ready -> acceleration (diskor); insufficient_evidence -> discovery (setelah acceleration, tanpa skor; unknown bukan peluang buruk).": "Sets the tier: ready -> acceleration (scored); insufficient_evidence -> discovery (after acceleration, no score; unknown does not mean a poor opportunity).",
  "Nilai CRM Rp168.000.000 belum divalidasi percakapan; dipakai hanya untuk urutan jadwal discovery antar-deal discovery.": "The CRM value Rp168.000.000 is not validated by conversation; it is used only to schedule discovery among discovery deals.",
  "Nilai deal adalah potensi CRM (outlet x harga acuan), bukan pendapatan.": "Deal value is CRM potential (outlets x reference price), not revenue.",
  "Nilai potensi tahunan lebih besar.": "Higher potential annual value.",
  "Overlap masa kerja tidak membuktikan saling kenal; hubungan pribadi dan izin pengantar belum dikonfirmasi.": "Employment overlap does not establish acquaintance; personal relationships and introduction consent are unconfirmed.",
  "P05: tidak ada interaksi eksternal bertanggal dalam jendela sumber; 0 email internal tercatat. Umur deal 5 hari.": "P05: no dated external interactions in the source window; 0 internal emails recorded. Deal age: 5 days.",
  "Pak Bagus, Direktur Utama kami minta rekomendasi dari pengguna yang mirip dengan kami sebelum tanda tangan. Kami tunda dulu sampai ada referensi.": "Mr Bagus, our President Director wants a recommendation from a similar user before signing. We are putting this on hold until there is a reference.",
  "Pelanggan meminta referensi; permintaan saja tidak membuktikan deal sudah tertunda atau referensi sudah diberikan.": "The customer requests a reference; a request alone does not prove the deal is on hold or a reference has been provided.",
  "Pengalaman terbaru pelanggan perlu dikonfirmasi; usage/indikator CRM bukan penilaian kelayakan.": "Recent customer experience needs confirmation; usage and CRM indicators do not establish suitability.",
  "Pengamatan umur prospek lintas tahap bukan distribusi pembanding per tahap/segmen; SLA juga belum tersedia. Nilai paling lama adalah deskripsi sampel, bukan dasar menyatakan outlier statistik.": "Prospect ages across stages are not a comparison distribution for each stage/segment; no SLA is available either. The longest age describes this sample and does not establish a statistical outlier.",
  "Percakapan mendukung keberatan harga; harga kompetitor yang disebut bukan permintaan atau approval diskon prospek.": "Conversation supports a price objection; the quoted competitor price is not a request for or approval of a prospect discount.",
  "Periksa keputusan dan log sebelum penawaran; diskon >10% memerlukan VP Sales serta pencatatan menurut kontrak tim.": "Check the decision and log before making an offer; discounts >10% require VP Sales and a record under the team contract.",
  "Periksa kesesuaian industri, skala dan kebutuhan; konfirmasikan pengalaman terbaru serta persetujuan kontak sebelum memakai kandidat sebagai referensi.": "Check industry, scale and needs; confirm recent experience and contact consent before using a candidate as a reference.",
  "Pesan pelanggan meminta referensi: Butuh modul apotek untuk 9 klinik. Bu Ratna minta referensi pelanggan apotek yang sudah memakai KasirNusa. CRM mencatat Apotek Bunda Sehat (C17), industri Apotek, 10 outlet. Usage FEAT-05 2026-09 mencatat 22 pengguna aktif.": "Customer reference request, translated: A pharmacy module is needed for 9 clinics. Ms Ratna requests a reference from a pharmacy customer already using KasirNusa. CRM records Apotek Bunda Sehat (C17), pharmacy industry, 10 outlets. FEAT-05 usage for 2026-09 records 22 active users.",
  "Pesan pelanggan meminta referensi: Butuh modul apotek untuk 9 klinik. Bu Ratna minta referensi pelanggan apotek yang sudah memakai KasirNusa. CRM mencatat Apotek Kimia Sejahtera (C27), industri Apotek, 22 outlet. Usage FEAT-05 2026-09 mencatat 48 pengguna aktif.": "Customer reference request, translated: A pharmacy module is needed for 9 clinics. Ms Ratna requests a reference from a pharmacy customer already using KasirNusa. CRM records Apotek Kimia Sejahtera (C27), pharmacy industry, 22 outlets. FEAT-05 usage for 2026-09 records 48 active users.",
  "Pesan pelanggan meminta referensi: Butuh modul apotek untuk 9 klinik. Bu Ratna minta referensi pelanggan apotek yang sudah memakai KasirNusa. CRM mencatat Apotek Medika Farma (C09), industri Apotek, 15 outlet. Usage FEAT-05 2026-09 mencatat 11 pengguna aktif.": "Customer reference request, translated: A pharmacy module is needed for 9 clinics. Ms Ratna requests a reference from a pharmacy customer already using KasirNusa. CRM records Apotek Medika Farma (C09), pharmacy industry, 15 outlets. FEAT-05 usage for 2026-09 records 11 active users.",
  "Pesan pelanggan meminta referensi: Butuh modul apotek untuk 9 klinik. Bu Ratna minta referensi pelanggan apotek yang sudah memakai KasirNusa. CRM mencatat Apotek Sehat Sentosa (C03), industri Apotek, 18 outlet. Usage FEAT-05 2026-09 mencatat 14 pengguna aktif.": "Customer reference request, translated: A pharmacy module is needed for 9 clinics. Ms Ratna requests a reference from a pharmacy customer already using KasirNusa. CRM records Apotek Sehat Sentosa (C03), pharmacy industry, 18 outlets. FEAT-05 usage for 2026-09 records 14 active users.",
  "Pesan pelanggan meminta referensi: Pak Bagus, Direktur Utama kami minta rekomendasi dari pengguna yang mirip dengan kami sebelum tanda tangan. Kami tunda dulu sampai ada referensi. CRM mencatat Saiyo Group (C06), industri Resto Padang, 30 outlet. Riwayat Hartono Gunawan dan Budi Santoso di PT Sentosa Abadi Group menghasilkan overlap 2015-02-01 sampai 2019-11-30. CRM saat ini mengaitkan Budi Santoso (CFO) dengan Saiyo Group (C06). Riwayat masa kerja aktif di akun tersebut mulai 2020-01-02.": "Customer reference request, translated: Mr Bagus, our President Director wants a recommendation from a similar user before signing. We are putting this on hold until there is a reference. CRM records Saiyo Group (C06), Padang restaurant industry, 30 outlets. Hartono Gunawan and Budi Santoso's history at PT Sentosa Abadi Group overlaps from 2015-02-01 to 2019-11-30. CRM currently links Budi Santoso (CFO) to Saiyo Group (C06). Active employment at that account started on 2020-01-02.",
  "Poin hambatan dinyatakan pelanggan lebih tinggi (deal yang ditahan pelanggan dengan syarat jelas ditangani dulu).": "Higher customer-stated blocker points (deals held by customers with explicit conditions are handled first).",
  "Prioritas tindakan deal (heuristik rules v1)": "Deal action priority (rules heuristic v1)",
  "Rank 1 adalah urutan perhatian sales pada snapshot 2026-10-01, bukan probabilitas closing.": "Rank 1 orders sales attention at the 2026-10-01 snapshot; it is not a closing probability.",
  "Rank 2 adalah urutan perhatian sales pada snapshot 2026-10-01, bukan probabilitas closing.": "Rank 2 orders sales attention at the 2026-10-01 snapshot; it is not a closing probability.",
  "Rank 3 adalah urutan perhatian sales pada snapshot 2026-10-01, bukan probabilitas closing.": "Rank 3 orders sales attention at the 2026-10-01 snapshot; it is not a closing probability.",
  "Rank 4 adalah urutan perhatian sales pada snapshot 2026-10-01, bukan probabilitas closing.": "Rank 4 orders sales attention at the 2026-10-01 snapshot; it is not a closing probability.",
  "Rank 5 adalah urutan perhatian sales pada snapshot 2026-10-01, bukan probabilitas closing.": "Rank 5 orders sales attention at the 2026-10-01 snapshot; it is not a closing probability.",
  "Rank adalah urutan perhatian/tindakan sales, bukan prediksi urutan closing atau penilaian kualitas pelanggan.": "Rank orders sales attention/actions; it does not predict closing order or rate customer quality.",
  "Ranking heuristik rules; belum tervalidasi terhadap hasil closing historis dan bukan probabilitas closing.": "Rules-based heuristic ranking; not validated against historical closing outcomes and not a closing probability.",
  "Relasi kanonis mendukung kandidat untuk pemeriksaan referensi, bukan ranking, kelayakan, perkenalan atau kesediaan pelanggan.": "Canonical relationships support candidates for reference checks, not ranking, suitability, introductions or customer willingness.",
  "Rina Hapsari (K017) merupakan kandidat identitas pemegang wewenang dari gabungan pesan, jabatan dan masa kerja, bukan penetapan langsung.": "Rina Hapsari (K017) is a candidate decision-maker identity based on messages, role and employment dates, not a direct determination.",
  "Rp147.000.000 = 2/3 poin (>= Rp200.000.000: 3; >= Rp100.000.000: 2; >= Rp50.000.000: 1; lainnya 0); potensi CRM, bukan pendapatan.": "Rp147.000.000 = 2/3 points (>= Rp200.000.000: 3; >= Rp100.000.000: 2; >= Rp50.000.000: 1; otherwise 0); CRM potential, not revenue.",
  "Rp168.000.000 = 2/3 poin (>= Rp200.000.000: 3; >= Rp100.000.000: 2; >= Rp50.000.000: 1; lainnya 0); potensi CRM, bukan pendapatan. Tier discovery: tidak dipakai menghitung skor. Dalam tier discovery dipakai sebagai urutan jadwal discovery.": "Rp168.000.000 = 2/3 points (>= Rp200.000.000: 3; >= Rp100.000.000: 2; >= Rp50.000.000: 1; otherwise 0); CRM potential, not revenue. Discovery tier: excluded from scoring; used to schedule discovery.",
  "Rp252.000.000 = 3/3 poin (>= Rp200.000.000: 3; >= Rp100.000.000: 2; >= Rp50.000.000: 1; lainnya 0); potensi CRM, bukan pendapatan.": "Rp252.000.000 = 3/3 points (>= Rp200.000.000: 3; >= Rp100.000.000: 2; >= Rp50.000.000: 1; otherwise 0); CRM potential, not revenue.",
  "Rp37.800.000 = 0/3 poin (>= Rp200.000.000: 3; >= Rp100.000.000: 2; >= Rp50.000.000: 1; lainnya 0); potensi CRM, bukan pendapatan.": "Rp37.800.000 = 0/3 points (>= Rp200.000.000: 3; >= Rp100.000.000: 2; >= Rp50.000.000: 1; otherwise 0); CRM potential, not revenue.",
  "Rp63.000.000 = 1/3 poin (>= Rp200.000.000: 3; >= Rp100.000.000: 2; >= Rp50.000.000: 1; lainnya 0); potensi CRM, bukan pendapatan.": "Rp63.000.000 = 1/3 points (>= Rp200.000.000: 3; >= Rp100.000.000: 2; >= Rp50.000.000: 1; otherwise 0); CRM potential, not revenue.",
  "Rules deterministik pilihan desain, bukan model terlatih. Tier acceleration (status ready) diurutkan sebelum tier discovery (insufficient_evidence). Skor acceleration = tahap_deal (0-4) + nilai_potensi_tahunan (0-3) + hambatan_dinyatakan_pelanggan (0-2) + preseden_relevan (0-1), maksimum 10; bobot dan aturan bin ada di field weights. Approval/izin adalah gate dari analisis rules dan tidak memengaruhi skor. Rank = urutan perhatian/tindakan sales pada snapshot, bukan probabilitas closing.": "Deterministic design rules, not a trained model. The acceleration tier (ready) precedes discovery (insufficient_evidence). Acceleration score = deal stage (0–4) + potential annual value (0–3) + customer-stated blocker (0–2) + relevant precedent (0–1), maximum 10; weights and band rules appear under weights. Approval/consent are rules-based requirements and do not affect the score. Rank orders sales attention/actions at the snapshot; it is not a closing probability.",
  "SKENARIO | Pilot maks 10 outlet paket Starter = Rp42.000.000/tahun; 5 outlet sisanya butuh paket Growth. Usulan, belum disetujui pelanggan/VP Sales.": "SCENARIO | A maximum 10-outlet Starter pilot = Rp42.000.000/year; the remaining 5 outlets need Growth. A proposal, not approved by the customer or VP Sales.",
  "Sensitivitas bobot nilai x2: urutan acceleration DL-001 > DL-004 > DL-002 > DL-003 (berubah dari DL-004 > DL-001 > DL-002 > DL-003).": "Sensitivity with value weighted x2: acceleration order DL-001 > DL-004 > DL-002 > DL-003 (changed from DL-004 > DL-001 > DL-002 > DL-003).",
  "Sensitivitas tanpa faktor hambatan_dinyatakan_pelanggan: urutan acceleration DL-001 > DL-004 > DL-002 > DL-003 (berubah dari DL-004 > DL-001 > DL-002 > DL-003).": "Sensitivity without customer-stated blocker: acceleration order DL-001 > DL-004 > DL-002 > DL-003 (changed from DL-004 > DL-001 > DL-002 > DL-003).",
  "Sensitivitas tanpa faktor nilai_potensi_tahunan: urutan acceleration DL-004 > DL-001 > DL-002 > DL-003 (sama).": "Sensitivity without potential annual value: acceleration order DL-004 > DL-001 > DL-002 > DL-003 (unchanged).",
  "Sensitivitas tanpa faktor preseden_relevan: urutan acceleration DL-004 > DL-001 > DL-002 > DL-003 (sama).": "Sensitivity without relevant precedent: acceleration order DL-004 > DL-001 > DL-002 > DL-003 (unchanged).",
  "Sensitivitas tanpa faktor tahap_deal: urutan acceleration DL-001 > DL-004 > DL-002 > DL-003 (berubah dari DL-004 > DL-001 > DL-002 > DL-003).": "Sensitivity without deal stage: acceleration order DL-001 > DL-004 > DL-002 > DL-003 (changed from DL-004 > DL-001 > DL-002 > DL-003).",
  "Skor acceleration = jumlah poin empat faktor terhitung (lihat weights); urut skor menurun.": "Acceleration score = total points from the four scored factors (see weights); sorted by descending score.",
  "Tahap Demo = 2/4 poin (Lead 0, Discovery 1, Demo 2, Proposal 3, Negosiasi 4 (crm_deals.stage)).": "Demo stage = 2/4 points (Lead 0, Discovery 1, Demo 2, Proposal 3, Negotiation 4 (crm_deals.stage)).",
  "Tahap Discovery = 1/4 poin (Lead 0, Discovery 1, Demo 2, Proposal 3, Negosiasi 4 (crm_deals.stage)).": "Discovery stage = 1/4 points (Lead 0, Discovery 1, Demo 2, Proposal 3, Negotiation 4 (crm_deals.stage)).",
  "Tahap Lead = 0/4 poin (Lead 0, Discovery 1, Demo 2, Proposal 3, Negosiasi 4 (crm_deals.stage)). Tier discovery: tidak dipakai menghitung skor.": "Lead stage = 0/4 points (Lead 0, Discovery 1, Demo 2, Proposal 3, Negotiation 4 (crm_deals.stage)). Discovery tier: excluded from scoring.",
  "Tahap Negosiasi = 4/4 poin (Lead 0, Discovery 1, Demo 2, Proposal 3, Negosiasi 4 (crm_deals.stage)).": "Negotiation stage = 4/4 points (Lead 0, Discovery 1, Demo 2, Proposal 3, Negotiation 4 (crm_deals.stage)).",
  "Tahap Proposal = 3/4 poin (Lead 0, Discovery 1, Demo 2, Proposal 3, Negosiasi 4 (crm_deals.stage)).": "Proposal stage = 3/4 points (Lead 0, Discovery 1, Demo 2, Proposal 3, Negotiation 4 (crm_deals.stage)).",
  "Tahap lebih lanjut berarti tindakan berikutnya lebih dekat ke keputusan pembelian.": "A later stage means the next action is closer to a purchasing decision.",
  "Tahap lebih lanjut.": "Later stage.",
  "Tidak ada percakapan akun fokus yang cukup dalam sumber; aktivitas di luar dataset tidak diketahui.": "Insufficient conversation from the account in the sources; activity outside the dataset is unknown.",
  "Tidak ada preseden relevan di candidate_decisions = 0/1 poin.": "No relevant precedent in candidate_decisions = 0/1 point.",
  "Tidak ada preseden relevan di candidate_decisions = 0/1 poin. Tier discovery: tidak dipakai menghitung skor.": "No relevant precedent in candidate_decisions = 0/1 point. Discovery tier: excluded from scoring.",
  "Tidak dihitung: bukti percakapan belum cukup untuk dibandingkan.": "Not scored: insufficient conversation evidence for comparison.",
  "Tier acceleration (status ready): hambatan \"harga\" bersumber dari percakapan akun fokus. Skor 5/10 = tahap 2/4 + nilai 1/3 + hambatan pelanggan 1/2 + preseden 1/1.": "Acceleration tier (ready): the price blocker is supported by this account's conversations. Score 5/10 = stage 2/4 + value 1/3 + customer blocker 1/2 + precedent 1/1.",
  "Tier acceleration (status ready): hambatan \"pengambil_keputusan\" bersumber dari percakapan akun fokus. Skor 8/10 = tahap 3/4 + nilai 3/3 + hambatan pelanggan 1/2 + preseden 1/1.": "Acceleration tier (ready): the decision-maker blocker is supported by this account's conversations. Score 8/10 = stage 3/4 + value 3/3 + customer blocker 1/2 + precedent 1/1.",
  "Tier acceleration (status ready): hambatan \"referensi\" bersumber dari percakapan akun fokus. Skor 2/10 = tahap 1/4 + nilai 0/3 + hambatan pelanggan 1/2 + preseden 0/1.": "Acceleration tier (ready): the reference blocker is supported by this account's conversations. Score 2/10 = stage 1/4 + value 0/3 + customer blocker 1/2 + precedent 0/1.",
  "Tier acceleration (status ready): hambatan \"referensi\" bersumber dari percakapan akun fokus. Skor 8/10 = tahap 4/4 + nilai 2/3 + hambatan pelanggan 2/2 + preseden 0/1.": "Acceleration tier (ready): the reference blocker is supported by this account's conversations. Score 8/10 = stage 4/4 + value 2/3 + customer blocker 2/2 + precedent 0/1.",
  "Tier discovery (status insufficient_evidence): percakapan akun fokus belum cukup untuk menilai hambatan, sehingga ditempatkan setelah 4 deal acceleration tanpa skor. Ini bukan bukti peluang buruk, kalah, atau risiko rendah.": "Discovery tier (insufficient_evidence): conversations do not sufficiently establish blockers, so this deal follows the 4 acceleration deals without a score. This does not establish a poor opportunity, a loss or low risk.",
  "Tier: ready -> acceleration; insufficient_evidence -> discovery. Semua acceleration sebelum discovery.": "Tier: ready -> acceleration; insufficient_evidence -> discovery. All acceleration deals precede discovery.",
  "Tindakan berikutnya (owner E06): E06 meminta kontak teknis memperkenalkan dan menjadwalkan pertemuan langsung dengan Rina Hapsari (GM Operations, identitas inferensi yang perlu dikonfirmasi); sesuaikan proposal dengan prioritas operasional.": "Next action (owner E06): E06 asks the technical contact to introduce and schedule a direct meeting with Rina Hapsari (GM Operations; inferred identity requiring confirmation); align the proposal with operational priorities.",
  "Tindakan berikutnya (owner E06): E06 mengonfirmasi kriteria \"pengguna serupa\" atas permintaan I0335, lalu meminta account manager memeriksa pengalaman terbaru dan menanyakan kesediaan serta izin kontak Saiyo Group (C06, AM E04) sebelum perkenalan ke Nirwana Hotel & Resto.": "Next action (owner E06): E06 confirms the criteria for a similar user requested in I0335, then asks the account manager to check recent experience and obtain willingness and contact consent from Saiyo Group (C06, AM E04) before an introduction to Nirwana Hotel & Resto.",
  "Tindakan berikutnya (owner E07): E07 menjadwalkan discovery dengan PT Distribusi Sumber Rejeki untuk mengidentifikasi pengambil keputusan, kebutuhan, jumlah outlet dan anggaran sebelum menawarkan harga atau paket.": "Next action (owner E07): E07 schedules discovery with PT Distribusi Sumber Rejeki to identify the decision-maker, needs, outlet count and budget before offering a price or plan.",
  "Tindakan berikutnya (owner E07): Jangan menawarkan atau menjanjikan diskon 20% ke Teras Kafe Group sebelum VP Sales memutuskan dan mencatatnya.": "Next action (owner E07): Do not offer or promise a 20% discount to Teras Kafe Group before VP Sales decides and records it.",
  "Tindakan berikutnya (owner E08): E08 mengonfirmasi kriteria \"pengguna serupa\" atas permintaan I0334, lalu meminta account manager memeriksa pengalaman terbaru dan menanyakan kesediaan serta izin kontak Apotek Bunda Sehat (C17, AM E05), Apotek Medika Farma (C09, AM E03), Apotek Kimia Sejahtera (C27, AM E04) sebelum perkenalan ke Klinik Pratama Medika.": "Next action (owner E08): E08 confirms the criteria for a similar user requested in I0334, then asks the account manager to check recent experience and obtain willingness and contact consent from Apotek Bunda Sehat (C17, AM E05), Apotek Medika Farma (C09, AM E03) and Apotek Kimia Sejahtera (C27, AM E04) before an introduction to Klinik Pratama Medika.",
  "Umur tahap tidak dibandingkan lintas tahap; outlier statistik tidak dinilai.": "Stage ages are not compared across stages; statistical outliers are not assessed.",
  "Usulan sales adalah permintaan, bukan approval. Log akun lain atau log tanpa deal_id tidak mengesahkan permintaan deal fokus.": "A sales proposal is a request, not approval. Other accounts' logs or logs without a deal_id do not authorize the request for this deal.",
  "Validasi input: pasangkan context dan diagnostic per deal_id; tolak duplikasi, set deal berbeda, akun berbeda, snapshot campuran dan evidence ID sama dengan isi berbeda.": "Input validation: match context and diagnostics by deal_id; reject duplicates, different deal sets, different accounts, mixed snapshots and identical evidence IDs with conflicting content.",
  "Validasi kriteria referensi dengan prospek; periksa kandidat bersumber bersama account owner dan minta izin sebelum memperkenalkan.": "Validate reference criteria with the prospect; check sourced candidates with the account owner and request permission before an introduction.",
  "approval VP Sales tertunda": "VP Sales approval pending",
  "business_anomaly berarti hambatan/ketidakselarasan yang didukung percakapan, bukan pelanggaran SLA yang belum tersedia.": "business_anomaly means a blocker or inconsistency supported by conversation, not a breach of an unavailable SLA.",
  "deal_id leksikografis; hanya agar hasil deterministik, bukan prioritas bisnis.": "Lexicographic deal_id; only for deterministic results, not business priority.",
  "discovery belum dilakukan": "Discovery not yet completed",
  "kesediaan/izin kandidat referensi belum ada": "Reference candidate willingness/consent unavailable",
  "pelanggan menyatakan hambatan (I0296:customer, I0348:internal) = 1/2 poin.": "Customer-stated blocker (I0296:customer, I0348:internal) = 1/2 point.",
  "pelanggan menyatakan hambatan (I0334:customer) = 1/2 poin.": "Customer-stated blocker (I0334:customer) = 1/2 point.",
  "pelanggan menyatakan hambatan (I0343:customer) = 1/2 poin.": "Customer-stated blocker (I0343:customer) = 1/2 point.",
  "pelanggan menyatakan penundaan/syarat (I0335:customer) = 2/2 poin.": "Customer-stated delay/condition (I0335:customer) = 2/2 points.",
  "pesan pelanggan menyatakan penundaan/syarat: 2; pesan pelanggan menyatakan hambatan: 1; hambatan hanya dari pesan internal: 0": "Customer-stated delay/condition: 2; customer-stated blocker: 1; blocker only in internal messages: 0",
  "D-2024-02 (2024-04-03, diskon, akun C15): 20% -> Ditolak oleh E01; alasan: Di luar kebijakan; ditawarkan 10%": "D-2024-02 (2024-04-03, discount, account C15): 20% -> Rejected by E01; reason: Outside policy; 10% offered",
  "D-2025-02 (2025-03-04, diskon, akun C23): 20% -> Ditolak oleh E01; alasan: Di atas batas 15%; menyamai harga kompetitor merusak harga pasar. Deal kemudian kalah karena harga.": "D-2025-02 (2025-03-04, discount, account C23): 20% -> Rejected by E01; reason: Above the 15% limit; matching competitor prices harms market pricing. The deal was later lost on price.",
  "D-2025-06 (2025-08-12, pengecualian, akun C23): Paket Starter tanpa diskon, pilot 6 outlet -> Disetujui oleh E01; alasan: Pendekatan alternatif setelah kalah Maret: mulai dari Starter, naik paket bila puas. Deal menang Sep 2025.": "D-2025-06 (2025-08-12, exception, account C23): Starter plan without a discount, 6-outlet pilot -> Approved by E01; reason: An alternative after the March loss: start on Starter and upgrade if satisfied. The deal was won in Sep 2025.",
  "D-2025-11 (2025-11-28, diskon, akun C01): 15% -> Disetujui oleh E01; alasan: Pengecualian: akun strategis 42 outlet; komitmen integrasi akuntansi rilis Q3 2026": "D-2025-11 (2025-11-28, discount, account C01): 15% -> Approved by E01; reason: Exception for a strategic account with 42 outlets; commitment to release accounting integration in Q3 2026",
  "D-2025-11: janji fitur FEAT-07 berstatus 'Belum ditepati'.": "D-2025-11: the FEAT-07 feature promise is marked 'Not fulfilled'.",
  "D-2025-12 (2025-12-09, diskon, akun C33): 18% -> Ditolak oleh E01; alasan: Volume kecil": "D-2025-12 (2025-12-09, discount, account C33): 18% -> Rejected by E01; reason: Small volume",
  "D-2026-04 (2026-03-26, diskon, akun C21): 20% -> Ditolak oleh E01; alasan: Di luar kebijakan; ditawarkan Starter": "D-2026-04 (2026-03-26, discount, account C21): 20% -> Rejected by E01; reason: Outside policy; Starter offered",
  "D-2026-08 (2026-07-14, eskalasi, akun C01): Kepastian jadwal FEAT-07 -> Menunggu oleh E09; alasan: Klien menanyakan jadwal integrasi; belum ada tanggal dari produk": "D-2026-08 (2026-07-14, escalation, account C01): Confirm the FEAT-07 schedule -> Pending with E09; reason: The client asked about the integration schedule; no date from product yet",
  "DL-001 Grup Ritel Mandala: stage Proposal sejak 2026-09-11 (20 hari per 2026-10-01); nilai potensi tahunan Rp252.000.000 (bukan pendapatan).": "DL-001 Grup Ritel Mandala: Proposal stage since 2026-09-11 (20 days as of 2026-10-01); potential annual value Rp252.000.000 (not revenue).",
  "DL-002 Teras Kafe Group: stage Demo sejak 2026-08-17 (45 hari per 2026-10-01); nilai potensi tahunan Rp63.000.000 (bukan pendapatan); kompetitor tercatat: KasirPro.": "DL-002 Teras Kafe Group: Demo stage since 2026-08-17 (45 days as of 2026-10-01); potential annual value Rp63.000.000 (not revenue); recorded competitor: KasirPro.",
  "DL-003 Klinik Pratama Medika: stage Discovery sejak 2026-09-21 (10 hari per 2026-10-01); nilai potensi tahunan Rp37.800.000 (bukan pendapatan).": "DL-003 Klinik Pratama Medika: Discovery stage since 2026-09-21 (10 days as of 2026-10-01); potential annual value Rp37.800.000 (not revenue).",
  "DL-004 Nirwana Hotel & Resto: stage Negosiasi sejak 2026-09-01 (30 hari per 2026-10-01); nilai potensi tahunan Rp147.000.000 (bukan pendapatan).": "DL-004 Nirwana Hotel & Resto: Negotiation stage since 2026-09-01 (30 days as of 2026-10-01); potential annual value Rp147.000.000 (not revenue).",
  "DL-005 PT Distribusi Sumber Rejeki: stage Lead sejak 2026-09-26 (5 hari per 2026-10-01); nilai potensi tahunan Rp168.000.000 (bukan pendapatan).": "DL-005 PT Distribusi Sumber Rejeki: Lead stage since 2026-09-26 (5 days as of 2026-10-01); potential annual value Rp168.000.000 (not revenue).",
  "Deal preseden DL-006 juga mencatat kompetitor KasirPro (crm_deals.kompetitor).": "Precedent deal DL-006 also records competitor KasirPro (crm_deals.kompetitor).",
  "Deal preseden DL-007 juga mencatat kompetitor KasirPro (crm_deals.kompetitor).": "Precedent deal DL-007 also records competitor KasirPro (crm_deals.kompetitor).",
  "Di candidate_decisions konteks ini ada 6 keputusan diskon >10%: 1 disetujui (D-2025-11), 5 ditolak (D-2024-02, D-2024-06, D-2025-02, D-2025-12, D-2026-04).": "This context's candidate_decisions contain 6 decisions on discounts >10%: 1 approved (D-2025-11), 5 rejected (D-2024-02, D-2024-06, D-2025-02, D-2025-12, D-2026-04).",
  "Hitungan: 15 outlet x Rp350.000 x 12 = Rp63.000.000; diskon 20% -> Rp50.400.000 (berkurang Rp12.600.000).": "Calculation: 15 outlets x Rp350.000 x 12 = Rp63.000.000; 20% discount -> Rp50.400.000 (reduction of Rp12.600.000).",
  "I0269 (2026-07-30, P02): \"15 kafe di Malang dan Batu. Butuh POS dan stok bahan baku.\"": "I0269 (2026-07-30, P02), translated: \"15 cafes in Malang and Batu. POS and raw-material inventory are needed.\"",
  "I0296 (2026-08-17, P02): \"Pak Teddy suka produknya tetapi menilai harga terlalu tinggi. KasirPro menawarkan harga sekitar 20% lebih murah.\"": "I0296 (2026-08-17, P02), translated: \"Mr Teddy likes the product but considers the price too high. KasirPro offers a price around 20% lower.\"",
  "I0296: kompetitor disebut ~20% lebih murah (klaim, belum diverifikasi).": "I0296: the competitor is described as ~20% cheaper (unverified claim).",
  "I0334 (2026-09-21, P03): \"Butuh modul apotek untuk 9 klinik. Bu Ratna minta referensi pelanggan apotek yang sudah memakai KasirNusa.\"": "I0334 (2026-09-21, P03), translated: \"A pharmacy module is needed for 9 clinics. Ms Ratna requests a reference from a pharmacy customer already using KasirNusa.\"",
  "I0335 (2026-09-22, P04): \"Pak Bagus, Direktur Utama kami minta rekomendasi dari pengguna yang mirip dengan kami sebelum tanda tangan. Kami tunda dulu sampai ada referensi.\"": "I0335 (2026-09-22, P04), translated: \"Mr Bagus, our President Director wants a recommendation from a similar user before signing. We are putting this on hold until there is a reference.\"",
  "I0343 (2026-09-24, P01): \"Mas Bagus, proposal sudah saya teruskan ke GM Operations yang baru bergabung awal September. Keputusan pengadaan sistem kasir ada di beliau, saya hanya menilai sisi teknis.\"": "I0343 (2026-09-24, P01), translated: \"Bagus, I have forwarded the proposal to the GM Operations who joined in early September. The POS procurement decision is theirs; I only assess the technical side.\"",
  "I0348 (2026-09-28): PERMINTAAN diskon 20% (permintaan, bukan approval).": "I0348 (2026-09-28): REQUEST for a 20% discount (a request, not approval).",
  "I0348 (2026-09-28, P02): \"Pak Andi, untuk menutup Teras Kafe saya usul diskon 20% agar menyamai KasirPro. Mohon keputusan.\"": "I0348 (2026-09-28, P02), translated: \"Mr Andi, to close Teras Kafe I propose a 20% discount to match KasirPro. Please make a decision.\"",
  "K017 sebelumnya Head of Operations di Kopi Lintas Nusantara (2021-03-01 s.d. 2026-08-15).": "K017 was previously Head of Operations at Kopi Lintas Nusantara (2021-03-01 to 2026-08-15).",
  "K017 sebelumnya Operations Supervisor di PT Kreasi Kuliner (2016-06-01 s.d. 2021-02-28).": "K017 was previously Operations Supervisor at PT Kreasi Kuliner (2016-06-01 to 2021-02-28).",
  "Kandidat C03 Apotek Sehat Sentosa (urutan cek 4, cek_dengan_catatan): relasi feature_usage, shared_industry; Apotek, 18 outlet; health dashboard Kuning, NPS 8; usage FEAT-05 2026-09: 14 pengguna aktif.": "Candidate C03 Apotek Sehat Sentosa (check order 4, check with reservations): feature_usage and shared_industry relationships; pharmacy, 18 outlets; dashboard health Yellow, NPS 8; FEAT-05 usage in 2026-09: 14 active users.",
  "Kandidat C06 Saiyo Group (urutan cek 1, cek_pertama): relasi work_overlap; Resto Padang, 30 outlet; health dashboard Hijau, NPS 9.": "Candidate C06 Saiyo Group (check order 1, check first): work_overlap relationship; Padang restaurant, 30 outlets; dashboard health Green, NPS 9.",
  "Kandidat C09 Apotek Medika Farma (urutan cek 2, cek_pertama): relasi feature_usage, shared_industry; Apotek, 15 outlet; health dashboard Hijau, NPS 9; usage FEAT-05 2026-09: 11 pengguna aktif.": "Candidate C09 Apotek Medika Farma (check order 2, check first): feature_usage and shared_industry relationships; pharmacy, 15 outlets; dashboard health Green, NPS 9; FEAT-05 usage in 2026-09: 11 active users.",
  "Kandidat C17 Apotek Bunda Sehat (urutan cek 1, cek_pertama): relasi feature_usage, shared_industry; Apotek, 10 outlet; health dashboard Hijau, NPS 10; usage FEAT-05 2026-09: 22 pengguna aktif.": "Candidate C17 Apotek Bunda Sehat (check order 1, check first): feature_usage and shared_industry relationships; pharmacy, 10 outlets; dashboard health Green, NPS 10; FEAT-05 usage in 2026-09: 22 active users.",
  "Kandidat C27 Apotek Kimia Sejahtera (urutan cek 3, cek_pertama): relasi feature_usage, shared_industry; Apotek, 22 outlet; health dashboard Kuning, NPS 8; usage FEAT-05 2026-09: 48 pengguna aktif.": "Candidate C27 Apotek Kimia Sejahtera (check order 3, check first): feature_usage and shared_industry relationships; pharmacy, 22 outlets; dashboard health Yellow, NPS 8; FEAT-05 usage in 2026-09: 48 active users.",
  "Verifikasi Bima discount_request:DL-002:I0348:20: pencarian 30 record decision_log menemukan 0 log untuk P02/DL-002.": "Bima verification discount_request:DL-002:I0348:20: searching 30 decision_log records found 0 logs for P02/DL-002.",
  "Verifikasi kewenangan Bima (DL-001:authority:I0343) menunjuk kandidat yang sama: K017 (tetap inferred).": "Bima's authority verification (DL-001:authority:I0343) identifies the same candidate: K017 (still inferred).",
  "C03 catatan: health dashboard Kuning (indikator CRM, bisa tidak mutakhir).": "C03 note: dashboard health Yellow (a CRM indicator that may be outdated).",
  "C03 dicek belakangan: 6 tiket terbuka (3 bug, 1 prioritas Tinggi/Kritis; T0521, T0523, T0526, T0566, T0608, T0616; judul: Laporan tidak sesuai/Selisih transaksi/Sinkronisasi).": "Check C03 later: 6 open tickets (3 bugs, 1 High/Critical priority; T0521, T0523, T0526, T0566, T0608, T0616; subjects: inaccurate reports / transaction discrepancies / synchronization).",
  "C06 catatan: 1 tiket terbuka (0 bug, 0 prioritas Tinggi/Kritis; T0637; judul: Laci kasir tidak terbuka).": "C06 note: 1 open ticket (0 bugs, 0 High/Critical priority; T0637; subject: cash drawer does not open).",
  "C06 catatan: industri Resto Padang berbeda dari Hospitality; kemiripan perlu dicek.": "C06 note: the Padang restaurant industry differs from Hospitality; similarity needs checking.",
  "C06: overlap masa kerja K028 Hartono Gunawan (Direktur Utama) dan K116 Budi Santoso (CFO) di PT Sentosa Abadi Group (2015-02-01 s.d. 2019-11-30); overlap tidak membuktikan saling kenal (acquaintance belum dikonfirmasi).": "C06: K028 Hartono Gunawan (President Director) and K116 Budi Santoso (CFO) had overlapping employment at PT Sentosa Abadi Group (2015-02-01 to 2019-11-30); overlap does not prove they know each other (acquaintance unconfirmed).",
  "C27 catatan: health dashboard Kuning (indikator CRM, bisa tidak mutakhir).": "C27 note: dashboard health Yellow (a CRM indicator that may be outdated).",
  "C27: riwayat eskalasi D-2025-08: Bug struk ganda (BUG-398) (Disetujui).": "C27: escalation history D-2025-08: Duplicate receipt bug (BUG-398) (Approved).",
  "Diperiksa tetapi tidak cocok untuk hambatan ini: D-2024-01, D-2024-05, D-2025-08, D-2025-12.": "Checked but not relevant to this blocker: D-2024-01, D-2024-05, D-2025-08, D-2025-12.",
  "Diperiksa tetapi tidak cocok untuk hambatan ini: D-2024-05, D-2025-08, D-2026-06.": "Checked but not relevant to this blocker: D-2024-05, D-2025-08, D-2026-06.",
  "Diperiksa tetapi tidak cocok untuk hambatan ini: D-2024-06, D-2024-07, D-2025-04, D-2025-07, D-2025-11, D-2026-08, D-2026-09, D-2026-11.": "Checked but not relevant to this blocker: D-2024-06, D-2024-07, D-2025-04, D-2025-07, D-2025-11, D-2026-08, D-2026-09, D-2026-11.",
  "INFERENSI: I0343 menyebut \"GM Operations\" sebagai pemegang keputusan; satu-satunya kontak CRM P01 dengan jabatan itu adalah K017 Rina Hapsari (mulai 2026-09-01). Belum dikonfirmasi langsung.": "INFERENCE: I0343 identifies \"GM Operations\" as the decision-maker; the only P01 CRM contact with that role is K017 Rina Hapsari (since 2026-09-01). Not directly confirmed.",
  "Kandidat related_account_* adalah hasil pencarian bersumber; urutan cek bukan penilaian kelayakan. Kesesuaian, kesediaan menjadi referensi dan izin kontak belum diketahui (null).": "related_account_* candidates are retrieved from sources; check order is not a suitability assessment. Suitability, willingness to give a reference and contact consent are unknown (null).",
  "Risiko kepercayaan: D-2025-11 di C01 (FEAT-07; Belum ditepati). Rina Hapsari mungkin mengetahui pengalaman ini (inferensi dari riwayat kerja, belum dikonfirmasi).": "Trust risk: D-2025-11 at C01 (FEAT-07; Not fulfilled). Rina Hapsari may know about this experience (inferred from employment history, unconfirmed).",
  "Risiko kepercayaan: D-2026-08 di C01 (Kepastian jadwal FEAT-07; Menunggu). Rina Hapsari mungkin mengetahui pengalaman ini (inferensi dari riwayat kerja, belum dikonfirmasi).": "Trust risk: D-2026-08 at C01 (Confirm FEAT-07 schedule; Pending). Rina Hapsari may know about this experience (inferred from employment history, unconfirmed).",
  "[cocok] Alasan D-2025-02 menyebut batas 15%; ini catatan satu keputusan, bukan aturan universal. Aturan tertulis: diskon >10% butuh VP Sales.": "[matching] D-2025-02 mentions a 15% limit; this is one decision record, not a universal rule. Written policy: discounts >10% require VP Sales.",
  "[cocok] Permintaan 20% pada deal ini sama dengan D-2025-02 yang ditolak; preseden ini tidak mendukung asumsi bahwa permintaan sekarang akan disetujui; keputusan tetap wewenang VP Sales.": "[matching] This deal's 20% request matches the rejected D-2025-02 request; the precedent does not support assuming approval now. The decision remains with VP Sales.",
  "[sebagian] D-2025-06 adalah pengecualian yang diputuskan; satu keberhasilan lama bukan jaminan.": "[partial] D-2025-06 is a decided exception; one past success is not a guarantee.",
  "[sebagian] D-2025-11 di C01 masih terbuka (Belum ditepati); relevan sebagai risiko kepercayaan karena terkait riwayat kerja pengambil keputusan (inferensi), bukan pola harga.": "[partial] D-2025-11 at C01 is still open (Not fulfilled); relevant as a trust risk linked to the decision-maker's employment history (inference), not a pricing pattern.",
  "[sebagian] D-2025-12: diskon 18% (>10%) ditolak; berbeda dari permintaan [20]%.": "[partial] D-2025-12: an 18% discount (>10%) was rejected; different from the [20]% request.",
  "[sebagian] D-2026-08 di C01 masih terbuka (Menunggu); relevan sebagai risiko kepercayaan karena terkait riwayat kerja pengambil keputusan (inferensi), bukan pola harga.": "[partial] D-2026-08 at C01 is still open (Pending); relevant as a trust risk linked to the decision-maker's employment history (inference), not a pricing pattern.",
  "[sebagian] Paket Starter (maks 10 outlet) TIDAK dapat langsung menampung 15 outlet deal ini. Meniru D-2025-06 berarti pilot sebagian outlet: usulan skenario, belum disetujui pelanggan maupun VP Sales.": "[partial] Starter (maximum 10 outlets) CANNOT directly cover this deal's 15 outlets. Reusing D-2025-06 means a partial-outlet pilot: a proposed scenario, not approved by the customer or VP Sales.",
  "[sebagian] Permintaan 20% pada deal ini sama dengan D-2024-02 yang ditolak; preseden ini tidak mendukung asumsi bahwa permintaan sekarang akan disetujui; keputusan tetap wewenang VP Sales.": "[partial] This deal's 20% request matches the rejected D-2024-02 request; the precedent does not support assuming approval now. The decision remains with VP Sales.",
  "[sebagian] Permintaan 20% pada deal ini sama dengan D-2026-04 yang ditolak; preseden ini tidak mendukung asumsi bahwa permintaan sekarang akan disetujui; keputusan tetap wewenang VP Sales.": "[partial] This deal's 20% request matches the rejected D-2026-04 request; the precedent does not support assuming approval now. The decision remains with VP Sales.",
  "Pilot maks 10 outlet paket Starter = Rp42.000.000/tahun; 5 outlet sisanya butuh paket Growth. Usulan, belum disetujui pelanggan/VP Sales.": "A maximum 10-outlet Starter pilot = Rp42.000.000/year; the remaining 5 outlets need Growth. A proposal, not approved by the customer or VP Sales.",
  "Admin Keuangan": "Finance Administrator",
  "Admin Operasional": "Operations Administrator",
  "Aplikasi tertutup sendiri": "Application closes unexpectedly",
  "Approval diskon 15% Kopi Lintas": "15% discount approval for Kopi Lintas",
  "Barcode scanner tidak terbaca": "Barcode scanner not recognized",
  "Bug printer berdampak 3 akun": "Printer bug affects 3 accounts",
  "Bug struk ganda (BUG-398)": "Duplicate receipt bug (BUG-398)",
  "Bundling perangkat": "Hardware bundle",
  "Cara cetak ulang struk": "How to reprint a receipt",
  "Cara menambah kasir baru": "How to add a cashier",
  "Cara ubah harga promo": "How to change promotional prices",
  "Cetak surat jalan": "Print delivery notes",
  "Check-in rutin": "Routine check-in",
  "Dashboard multi-outlet": "Multi-outlet dashboard",
  "Dashboard multi-outlet untuk klien Enterprise": "Multi-outlet dashboard for Enterprise customers",
  "Data penjualan hilang": "Missing sales data",
  "Demo produk Mandala": "Mandala product demo",
  "Di atas batas 15%; menyamai harga kompetitor merusak harga pasar. Deal kemudian kalah karena harga.": "Above the 15% limit; matching competitor pricing harms market prices. The deal was later lost on price.",
  "Di luar kebijakan": "Outside policy",
  "Di luar kebijakan; ditawarkan 10%": "Outside policy; 10% offered",
  "Di luar kebijakan; ditawarkan Starter": "Outside policy; Starter offered",
  "Dicatat ke roadmap": "Added to the roadmap",
  "Direktur Klinik": "Clinic Director",
  "Direktur Utama": "President Director",
  "Disetujui": "Approved",
  "Diskon proyek kontraktor": "Contractor project discount",
  "Ditolak": "Rejected",
  "Ditutup - tidak dapat direproduksi": "Closed — could not reproduce",
  "E-faktur pajak": "Electronic tax invoice",
  "Ekspansi 3 outlet": "3-outlet expansion",
  "Ekspansi Jakarta 2027": "Jakarta expansion 2027",
  "Ekspor CSV laporan harian timeout di outlet besar": "Daily report CSV export times out at large outlets",
  "Ekspor jurnal ke Accurate gagal": "Journal export to Accurate fails",
  "Ekspor laporan harian gagal": "Daily report export fails",
  "Gambar produk tidak tampil": "Product images not displayed",
  "Gratis 1 bulan": "1 free month",
  "Harga grosir bertingkat": "Tiered wholesale pricing",
  "Info rilis versi baru": "New version release information",
  "Integrasi akuntansi (Jurnal & Accurate)": "Accounting integration (Jurnal & Accurate)",
  "Jadwal integrasi akuntansi": "Accounting integration schedule",
  "Jadwal pelatihan kasir": "Cashier training schedule",
  "Jadwal review penggunaan": "Usage review schedule",
  "Kartu stok per gudang": "Stock cards by warehouse",
  "Kepala Apotek": "Head Pharmacist",
  "Kepastian jadwal FEAT-07": "Confirm the FEAT-07 schedule",
  "Klien grosir, arus kas musiman": "Wholesale customer with seasonal cash flow",
  "Klien membuka cabang baru": "Customer opening a new branch",
  "Klien menanyakan jadwal integrasi; belum ada tanggal dari produk": "Customer asked about the integration schedule; no date from product yet",
  "Kompensasi downtime 2 hari": "Compensation for 2 days of downtime",
  "Konfirmasi pembayaran": "Payment confirmation",
  "Konfirmasi perpanjangan 2026": "2026 renewal confirmation",
  "Kontrak 2 tahun": "2-year contract",
  "Kontrak 2 tahun dibayar di muka": "2-year contract paid upfront",
  "Laci kasir tidak terbuka": "Cash drawer does not open",
  "Laporan bulanan penggunaan": "Monthly usage report",
  "Laporan margin per kategori barang": "Margin report by product category",
  "Laporan stok selisih pada transfer antar gudang": "Stock report discrepancies on inter-warehouse transfers",
  "Laporan tidak sesuai": "Inaccurate report",
  "Laporan transaksi tidak lengkap": "Incomplete transaction report",
  "Manajemen stok multi-gudang": "Multi-warehouse inventory",
  "Manajer Area": "Area Manager",
  "Manajer Operasional": "Operations Manager",
  "Mapping akun COA untuk integrasi": "Chart-of-accounts mapping for integration",
  "Meeting perkenalan dengan CFO baru": "Introductory meeting with the new CFO",
  "Menunggu": "Pending",
  "Migrasi data gratis": "Free data migration",
  "Minta faktur pajak": "Tax invoice request",
  "Mode offline + sinkronisasi": "Offline mode + synchronization",
  "Modul apotek (resep & batch obat)": "Pharmacy module (prescriptions & medication batches)",
  "Notifikasi stok minimum via WhatsApp": "Low-stock notifications via WhatsApp",
  "POS inti": "Core POS",
  "Paket Starter tanpa diskon, pilot 6 outlet": "Starter plan without a discount, 6-outlet pilot",
  "Pamit": "Farewell",
  "Pelatihan kasir baru": "New cashier training",
  "Pelatihan tambahan gratis": "Free additional training",
  "Pembayaran": "Payment",
  "Pembayaran tahunan di muka": "Annual payment upfront",
  "Pemilik": "Owner",
  "Penambahan 5 outlet": "5 additional outlets",
  "Pendekatan alternatif setelah kalah Maret: mulai dari Starter, naik paket bila puas. Deal menang Sep 2025.": "Alternative after the March loss: start on Starter, upgrade if satisfied. Deal won in Sep 2025.",
  "Pengecualian: akun strategis 42 outlet; komitmen integrasi akuntansi rilis Q3 2026": "Exception for a strategic account with 42 outlets; commitment to release accounting integration in Q3 2026",
  "Pengingat review & renewal": "Review & renewal reminder",
  "Perbaikan": "Fix",
  "Pergantian bagian keuangan klien": "Change in the customer's finance team",
  "Pergantian banyak kasir": "High cashier turnover",
  "Permintaan diskon 20% Teras Kafe": "20% discount request for Teras Kafe",
  "Permintaan pemilik": "Owner request",
  "Perpanjangan kontrak 2026": "2026 contract renewal",
  "Perubahan alamat penagihan": "Billing address change",
  "Printer struk tidak merespons": "Receipt printer not responding",
  "Prioritas perbaikan": "Fix priority",
  "Program loyalti pelanggan": "Customer loyalty program",
  "Program loyalti untuk klien F&B": "Loyalty program for F&B customers",
  "Proposal KasirNusa untuk 60 gerai": "KasirNusa proposal for 60 outlets",
  "Referensi publik untuk industri F&B": "Public reference for the F&B industry",
  "Rekonsiliasi manual 42 outlet memakan 3 hari": "Manual reconciliation for 42 outlets takes 3 days",
  "Rencana cabang baru": "New branch plan",
  "Renewal 3 tahun": "3-year renewal",
  "Retur barang ke supplier": "Return goods to supplier",
  "Satuan ganda (sak dan kg)": "Multiple units (sacks and kg)",
  "Scan barcode lambat": "Slow barcode scanning",
  "Selesai": "Resolved",
  "Selisih stok transfer (BUG-405)": "Stock transfer discrepancy (BUG-405)",
  "Selisih transaksi": "Transaction discrepancy",
  "Setting pajak restoran": "Restaurant tax settings",
  "Sinkronisasi": "Synchronization",
  "Staf IT": "IT Staff",
  "Status pengadaan": "Procurement status",
  "Struk ganda saat printer timeout": "Duplicate receipts when the printer times out",
  "Struk tercetak dua kali": "Receipt printed twice",
  "Supervisor Gudang": "Warehouse Supervisor",
  "Supervisor Toko": "Store Supervisor",
  "Tablet kasir rusak": "Cashier tablet malfunction",
  "Tagihan bulan ini": "This month's invoice",
  "Template faktur dengan logo cabang": "Invoice template with branch logo",
  "Tempo bayar 14 hari": "14-day payment terms",
  "Tempo bayar 30 hari": "30-day payment terms",
  "Tempo bayar 45 hari": "45-day payment terms",
  "Terbuka": "Open",
  "Terima kasih tim KasirNusa": "Thank you, KasirNusa team",
  "Tidak ada justifikasi volume": "No volume justification",
  "Tidak memenuhi syarat volume": "Does not meet volume requirements",
  "Tindak lanjut demo": "Demo follow-up",
  "Tindak lanjut meeting": "Meeting follow-up",
  "Training laporan stok": "Stock report training",
  "Transaksi mode offline sebagian tidak tersinkron ke server": "Some offline transactions do not synchronize to the server",
  "Ubah kategori produk": "Change product category",
  "Volume 20+ outlet": "Volume of 20+ outlets",
  "Volume kecil": "Small volume",
  "identitas pengambil keputusan masih inferred": "Decision-maker identity is still inferred",
  "pelanggan menyatakan hambatan": "Customer-stated blocker",
  "pelanggan menyatakan penundaan/syarat": "Customer-stated delay/condition",
  "Pelanggan menyatakan menunda sampai ada referensi.": "The customer states the deal is on hold until a reference is available.",
  "Jev tidak dipakai untuk ranking (engine_mode rules).": "Jev is not used for ranking (engine_mode rules).",
  "Tindakan punya pembanding historis yang dapat dijelaskan.": "The action has an explainable historical comparison.",
  "Potensi yang dipertaruhkan; dibin agar nominal tidak mendominasi.": "Potential value at stake; grouped into bands so the amount does not dominate.",
  "Belum ditepati": "Not fulfilled",
  "Hijau": "Green",
  "Kuning": "Yellow",
  "Merah": "Red",
  "Tinggi": "High",
  "Kritis": "Critical",
  "Apotek": "Pharmacy",
  "Klinik + apotek": "Clinic + pharmacy",
  "Resto Padang": "Padang restaurant",
  "cocok": "Matching",
  "sebagian": "Partial match",
  "cek_pertama": "Check first",
  "cek_dengan_catatan": "Check with reservations",
  "tidak ada gate tercatat": "No requirement recorded",
  "15 kafe di Malang dan Batu. Butuh POS dan stok bahan baku.": "15 cafes in Malang and Batu. POS and raw-material inventory are needed.",
  "Pak Teddy suka produknya tetapi menilai harga terlalu tinggi. KasirPro menawarkan harga sekitar 20% lebih murah.": "Mr Teddy likes the product but considers the price too high. KasirPro offers a price around 20% lower.",
  "Mas Bagus, proposal sudah saya teruskan ke GM Operations yang baru bergabung awal September. Keputusan pengadaan sistem kasir ada di beliau, saya hanya menilai sisi teknis.": "Bagus, I have forwarded the proposal to the GM Operations who joined in early September. The POS procurement decision is theirs; I only assess the technical side.",
  "Pak Andi, untuk menutup Teras Kafe saya usul diskon 20% agar menyamai KasirPro. Mohon keputusan.": "Mr Andi, to close Teras Kafe I propose a 20% discount to match KasirPro. Please make a decision.",
  "FAKTA | D-2025-02 diajukan oleh pemilik deal yang sama (E07).": "FACT | D-2025-02 was requested by the same deal owner (E07).",
  "FAKTA | D-2025-06 diajukan oleh pemilik deal yang sama (E07).": "FACT | D-2025-06 was requested by the same deal owner (E07).",
  "FAKTA | D-2025-12 diajukan oleh pemilik deal yang sama (E07).": "FACT | D-2025-12 was requested by the same deal owner (E07)."
};
/** Translate only reviewed strings; never guess, delete a condition, or alter source objects. */
export function englishText(text: string): string {
  const exact = ENGLISH[text] ?? CATALOG[text];
  if (exact !== undefined) return exact;
  if (text.startsWith('Re: ')) return 'Re: ' + englishText(text.slice(4));
  if (text.includes(' · ')) return text.split(' · ').map(englishText).join(' · ');
  return text;
}
const FIELDS: Record<string, string> = {
  "tahap_deal": "Deal stage",
  "nilai_potensi_tahunan": "Potential annual value",
  "hambatan_dinyatakan_pelanggan": "Customer-stated blocker",
  "preseden_relevan": "Relevant precedent",
  "gate_approval_izin": "Approval and consent requirements",
  "umur_tahap_hari": "Days in stage",
  "interaksi_eksternal_terakhir": "Last external interaction",
  "status_bukti": "Evidence status",
  "skor_prioritas": "Priority score",
  "nama": "Name",
  "jabatan": "Role",
  "jabatan_saat_ini": "Current role",
  "organisasi": "Organization",
  "mulai": "Start",
  "selesai": "End",
  "tanggal": "Date",
  "alasan": "Reason",
  "keputusan": "Decision",
  "nilai": "Value",
  "tipe": "Type",
  "diputuskan_oleh": "Decided by",
  "diminta_oleh": "Requested by",
  "pengguna_aktif": "Active users",
  "bulan": "Month",
  "judul": "Title",
  "industri": "Industry",
  "jumlah_outlet": "Outlet count",
  "kota": "City",
  "kompetitor": "Competitor",
  "fitur_dijanjikan": "Promised feature",
  "status_janji": "Promise status",
  "skor": "Score",
  "umur_tahap": "Stage age",
  "bobot": "Weight"
};
export const fieldLabel = (key: string) => FIELDS[key] ?? key.replaceAll('_', ' ');
